namespace Examen.Main
{
    partial class InformationObrozovaniySotrudnik
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(InformationObrozovaniySotrudnik));
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties29 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties30 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties31 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties32 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.bunifuElipse1 = new Bunifu.Framework.UI.BunifuElipse(this.components);
            this.bunifuPanel1 = new Bunifu.UI.WinForms.BunifuPanel();
            this.DGV_Obrazovanie = new Bunifu.UI.WinForms.BunifuDataGridView();
            this.tb_obrazovanie = new Bunifu.UI.WinForms.BunifuTextBox();
            this.tb_nazvanieUchrejdenia = new Bunifu.UI.WinForms.BunifuTextBox();
            this.tb_vuz = new Bunifu.UI.WinForms.BunifuTextBox();
            this.tb_kvalifikaziya2 = new Bunifu.UI.WinForms.BunifuTextBox();
            this.tb_professiaDrugaya = new Bunifu.UI.WinForms.BunifuTextBox();
            this.tb_professiyaOsnovnaya = new Bunifu.UI.WinForms.BunifuTextBox();
            this.tb_nazvanieUchrejdenia2 = new Bunifu.UI.WinForms.BunifuTextBox();
            this.tb_kvalifikaziya = new Bunifu.UI.WinForms.BunifuTextBox();
            this.tb_exit = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btn_del = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btn_upd = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btn_add = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.groupBox1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuPanel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.DGV_Obrazovanie)).BeginInit();
            this.SuspendLayout();
            // 
            // bunifuElipse1
            // 
            this.bunifuElipse1.ElipseRadius = 40;
            this.bunifuElipse1.TargetControl = this;
            // 
            // bunifuPanel1
            // 
            this.bunifuPanel1.BackgroundColor = System.Drawing.Color.Snow;
            this.bunifuPanel1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel1.BackgroundImage")));
            this.bunifuPanel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel1.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuPanel1.BorderRadius = 40;
            this.bunifuPanel1.BorderThickness = 1;
            this.bunifuPanel1.Controls.Add(this.groupBox1);
            this.bunifuPanel1.Controls.Add(this.tb_exit);
            this.bunifuPanel1.Controls.Add(this.btn_del);
            this.bunifuPanel1.Controls.Add(this.btn_upd);
            this.bunifuPanel1.Controls.Add(this.btn_add);
            this.bunifuPanel1.Controls.Add(this.tb_professiaDrugaya);
            this.bunifuPanel1.Controls.Add(this.tb_professiyaOsnovnaya);
            this.bunifuPanel1.Controls.Add(this.tb_nazvanieUchrejdenia2);
            this.bunifuPanel1.Controls.Add(this.tb_kvalifikaziya);
            this.bunifuPanel1.Controls.Add(this.tb_vuz);
            this.bunifuPanel1.Controls.Add(this.tb_kvalifikaziya2);
            this.bunifuPanel1.Controls.Add(this.tb_nazvanieUchrejdenia);
            this.bunifuPanel1.Controls.Add(this.tb_obrazovanie);
            this.bunifuPanel1.Controls.Add(this.DGV_Obrazovanie);
            this.bunifuPanel1.Location = new System.Drawing.Point(42, 40);
            this.bunifuPanel1.Name = "bunifuPanel1";
            this.bunifuPanel1.ShowBorders = true;
            this.bunifuPanel1.Size = new System.Drawing.Size(1426, 621);
            this.bunifuPanel1.TabIndex = 0;
            // 
            // DGV_Obrazovanie
            // 
            this.DGV_Obrazovanie.AllowCustomTheming = false;
            dataGridViewCellStyle1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle1.ForeColor = System.Drawing.Color.Black;
            this.DGV_Obrazovanie.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
            this.DGV_Obrazovanie.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.DGV_Obrazovanie.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(41)))));
            this.DGV_Obrazovanie.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.DGV_Obrazovanie.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.DGV_Obrazovanie.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = System.Drawing.Color.DodgerBlue;
            dataGridViewCellStyle2.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle2.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.DGV_Obrazovanie.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
            this.DGV_Obrazovanie.ColumnHeadersHeight = 40;
            this.DGV_Obrazovanie.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            this.DGV_Obrazovanie.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.DGV_Obrazovanie.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.Black;
            this.DGV_Obrazovanie.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.DGV_Obrazovanie.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            this.DGV_Obrazovanie.CurrentTheme.BackColor = System.Drawing.Color.White;
            this.DGV_Obrazovanie.CurrentTheme.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.DGV_Obrazovanie.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.DodgerBlue;
            this.DGV_Obrazovanie.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            this.DGV_Obrazovanie.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.White;
            this.DGV_Obrazovanie.CurrentTheme.HeaderStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            this.DGV_Obrazovanie.CurrentTheme.HeaderStyle.SelectionForeColor = System.Drawing.Color.White;
            this.DGV_Obrazovanie.CurrentTheme.Name = null;
            this.DGV_Obrazovanie.CurrentTheme.RowsStyle.BackColor = System.Drawing.Color.White;
            this.DGV_Obrazovanie.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.DGV_Obrazovanie.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.Black;
            this.DGV_Obrazovanie.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.DGV_Obrazovanie.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle3.BackColor = System.Drawing.Color.White;
            dataGridViewCellStyle3.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle3.ForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle3.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.DGV_Obrazovanie.DefaultCellStyle = dataGridViewCellStyle3;
            this.DGV_Obrazovanie.EnableHeadersVisualStyles = false;
            this.DGV_Obrazovanie.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.DGV_Obrazovanie.HeaderBackColor = System.Drawing.Color.DodgerBlue;
            this.DGV_Obrazovanie.HeaderBgColor = System.Drawing.Color.Empty;
            this.DGV_Obrazovanie.HeaderForeColor = System.Drawing.Color.White;
            this.DGV_Obrazovanie.Location = new System.Drawing.Point(0, 0);
            this.DGV_Obrazovanie.Name = "DGV_Obrazovanie";
            this.DGV_Obrazovanie.RowHeadersVisible = false;
            this.DGV_Obrazovanie.RowTemplate.Height = 40;
            this.DGV_Obrazovanie.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.DGV_Obrazovanie.Size = new System.Drawing.Size(1426, 329);
            this.DGV_Obrazovanie.TabIndex = 1;
            this.DGV_Obrazovanie.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Light;
            // 
            // tb_obrazovanie
            // 
            this.tb_obrazovanie.AcceptsReturn = false;
            this.tb_obrazovanie.AcceptsTab = false;
            this.tb_obrazovanie.AnimationSpeed = 200;
            this.tb_obrazovanie.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tb_obrazovanie.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tb_obrazovanie.BackColor = System.Drawing.Color.Transparent;
            this.tb_obrazovanie.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tb_obrazovanie.BackgroundImage")));
            this.tb_obrazovanie.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tb_obrazovanie.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tb_obrazovanie.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tb_obrazovanie.BorderColorIdle = System.Drawing.Color.Silver;
            this.tb_obrazovanie.BorderRadius = 40;
            this.tb_obrazovanie.BorderThickness = 1;
            this.tb_obrazovanie.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tb_obrazovanie.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_obrazovanie.DefaultFont = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Italic);
            this.tb_obrazovanie.DefaultText = "";
            this.tb_obrazovanie.FillColor = System.Drawing.Color.White;
            this.tb_obrazovanie.HideSelection = true;
            this.tb_obrazovanie.IconLeft = null;
            this.tb_obrazovanie.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_obrazovanie.IconPadding = 10;
            this.tb_obrazovanie.IconRight = null;
            this.tb_obrazovanie.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_obrazovanie.Lines = new string[0];
            this.tb_obrazovanie.Location = new System.Drawing.Point(3, 360);
            this.tb_obrazovanie.MaxLength = 32767;
            this.tb_obrazovanie.MinimumSize = new System.Drawing.Size(1, 1);
            this.tb_obrazovanie.Modified = false;
            this.tb_obrazovanie.Multiline = false;
            this.tb_obrazovanie.Name = "tb_obrazovanie";
            stateProperties29.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties29.FillColor = System.Drawing.Color.Empty;
            stateProperties29.ForeColor = System.Drawing.Color.Empty;
            stateProperties29.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_obrazovanie.OnActiveState = stateProperties29;
            stateProperties30.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties30.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties30.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties30.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tb_obrazovanie.OnDisabledState = stateProperties30;
            stateProperties31.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties31.FillColor = System.Drawing.Color.Empty;
            stateProperties31.ForeColor = System.Drawing.Color.Empty;
            stateProperties31.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_obrazovanie.OnHoverState = stateProperties31;
            stateProperties32.BorderColor = System.Drawing.Color.Silver;
            stateProperties32.FillColor = System.Drawing.Color.White;
            stateProperties32.ForeColor = System.Drawing.Color.Empty;
            stateProperties32.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_obrazovanie.OnIdleState = stateProperties32;
            this.tb_obrazovanie.Padding = new System.Windows.Forms.Padding(3);
            this.tb_obrazovanie.PasswordChar = '\0';
            this.tb_obrazovanie.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tb_obrazovanie.PlaceholderText = "Введите оброзование";
            this.tb_obrazovanie.ReadOnly = false;
            this.tb_obrazovanie.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tb_obrazovanie.SelectedText = "";
            this.tb_obrazovanie.SelectionLength = 0;
            this.tb_obrazovanie.SelectionStart = 0;
            this.tb_obrazovanie.ShortcutsEnabled = true;
            this.tb_obrazovanie.Size = new System.Drawing.Size(540, 42);
            this.tb_obrazovanie.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tb_obrazovanie.TabIndex = 10;
            this.tb_obrazovanie.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tb_obrazovanie.TextMarginBottom = 0;
            this.tb_obrazovanie.TextMarginLeft = 3;
            this.tb_obrazovanie.TextMarginTop = 0;
            this.tb_obrazovanie.TextPlaceholder = "Введите оброзование";
            this.tb_obrazovanie.UseSystemPasswordChar = false;
            this.tb_obrazovanie.WordWrap = true;
            // 
            // tb_nazvanieUchrejdenia
            // 
            this.tb_nazvanieUchrejdenia.AcceptsReturn = false;
            this.tb_nazvanieUchrejdenia.AcceptsTab = false;
            this.tb_nazvanieUchrejdenia.AnimationSpeed = 200;
            this.tb_nazvanieUchrejdenia.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tb_nazvanieUchrejdenia.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tb_nazvanieUchrejdenia.BackColor = System.Drawing.Color.Transparent;
            this.tb_nazvanieUchrejdenia.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tb_nazvanieUchrejdenia.BackgroundImage")));
            this.tb_nazvanieUchrejdenia.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tb_nazvanieUchrejdenia.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tb_nazvanieUchrejdenia.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tb_nazvanieUchrejdenia.BorderColorIdle = System.Drawing.Color.Silver;
            this.tb_nazvanieUchrejdenia.BorderRadius = 40;
            this.tb_nazvanieUchrejdenia.BorderThickness = 1;
            this.tb_nazvanieUchrejdenia.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tb_nazvanieUchrejdenia.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_nazvanieUchrejdenia.DefaultFont = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Italic);
            this.tb_nazvanieUchrejdenia.DefaultText = "";
            this.tb_nazvanieUchrejdenia.FillColor = System.Drawing.Color.White;
            this.tb_nazvanieUchrejdenia.HideSelection = true;
            this.tb_nazvanieUchrejdenia.IconLeft = null;
            this.tb_nazvanieUchrejdenia.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_nazvanieUchrejdenia.IconPadding = 10;
            this.tb_nazvanieUchrejdenia.IconRight = null;
            this.tb_nazvanieUchrejdenia.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_nazvanieUchrejdenia.Lines = new string[0];
            this.tb_nazvanieUchrejdenia.Location = new System.Drawing.Point(3, 408);
            this.tb_nazvanieUchrejdenia.MaxLength = 32767;
            this.tb_nazvanieUchrejdenia.MinimumSize = new System.Drawing.Size(1, 1);
            this.tb_nazvanieUchrejdenia.Modified = false;
            this.tb_nazvanieUchrejdenia.Multiline = false;
            this.tb_nazvanieUchrejdenia.Name = "tb_nazvanieUchrejdenia";
            stateProperties25.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties25.FillColor = System.Drawing.Color.Empty;
            stateProperties25.ForeColor = System.Drawing.Color.Empty;
            stateProperties25.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_nazvanieUchrejdenia.OnActiveState = stateProperties25;
            stateProperties26.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties26.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties26.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties26.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tb_nazvanieUchrejdenia.OnDisabledState = stateProperties26;
            stateProperties27.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties27.FillColor = System.Drawing.Color.Empty;
            stateProperties27.ForeColor = System.Drawing.Color.Empty;
            stateProperties27.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_nazvanieUchrejdenia.OnHoverState = stateProperties27;
            stateProperties28.BorderColor = System.Drawing.Color.Silver;
            stateProperties28.FillColor = System.Drawing.Color.White;
            stateProperties28.ForeColor = System.Drawing.Color.Empty;
            stateProperties28.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_nazvanieUchrejdenia.OnIdleState = stateProperties28;
            this.tb_nazvanieUchrejdenia.Padding = new System.Windows.Forms.Padding(3);
            this.tb_nazvanieUchrejdenia.PasswordChar = '\0';
            this.tb_nazvanieUchrejdenia.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tb_nazvanieUchrejdenia.PlaceholderText = "Введите наименование оброзовательного учереждения";
            this.tb_nazvanieUchrejdenia.ReadOnly = false;
            this.tb_nazvanieUchrejdenia.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tb_nazvanieUchrejdenia.SelectedText = "";
            this.tb_nazvanieUchrejdenia.SelectionLength = 0;
            this.tb_nazvanieUchrejdenia.SelectionStart = 0;
            this.tb_nazvanieUchrejdenia.ShortcutsEnabled = true;
            this.tb_nazvanieUchrejdenia.Size = new System.Drawing.Size(540, 42);
            this.tb_nazvanieUchrejdenia.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tb_nazvanieUchrejdenia.TabIndex = 11;
            this.tb_nazvanieUchrejdenia.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tb_nazvanieUchrejdenia.TextMarginBottom = 0;
            this.tb_nazvanieUchrejdenia.TextMarginLeft = 3;
            this.tb_nazvanieUchrejdenia.TextMarginTop = 0;
            this.tb_nazvanieUchrejdenia.TextPlaceholder = "Введите наименование оброзовательного учереждения";
            this.tb_nazvanieUchrejdenia.UseSystemPasswordChar = false;
            this.tb_nazvanieUchrejdenia.WordWrap = true;
            // 
            // tb_vuz
            // 
            this.tb_vuz.AcceptsReturn = false;
            this.tb_vuz.AcceptsTab = false;
            this.tb_vuz.AnimationSpeed = 200;
            this.tb_vuz.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tb_vuz.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tb_vuz.BackColor = System.Drawing.Color.Transparent;
            this.tb_vuz.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tb_vuz.BackgroundImage")));
            this.tb_vuz.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tb_vuz.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tb_vuz.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tb_vuz.BorderColorIdle = System.Drawing.Color.Silver;
            this.tb_vuz.BorderRadius = 40;
            this.tb_vuz.BorderThickness = 1;
            this.tb_vuz.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tb_vuz.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_vuz.DefaultFont = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Italic);
            this.tb_vuz.DefaultText = "";
            this.tb_vuz.FillColor = System.Drawing.Color.White;
            this.tb_vuz.HideSelection = true;
            this.tb_vuz.IconLeft = null;
            this.tb_vuz.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_vuz.IconPadding = 10;
            this.tb_vuz.IconRight = null;
            this.tb_vuz.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_vuz.Lines = new string[0];
            this.tb_vuz.Location = new System.Drawing.Point(549, 408);
            this.tb_vuz.MaxLength = 32767;
            this.tb_vuz.MinimumSize = new System.Drawing.Size(1, 1);
            this.tb_vuz.Modified = false;
            this.tb_vuz.Multiline = false;
            this.tb_vuz.Name = "tb_vuz";
            stateProperties17.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_vuz.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tb_vuz.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_vuz.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_vuz.OnIdleState = stateProperties20;
            this.tb_vuz.Padding = new System.Windows.Forms.Padding(3);
            this.tb_vuz.PasswordChar = '\0';
            this.tb_vuz.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tb_vuz.PlaceholderText = "Введите послевузовское профессиональное образование";
            this.tb_vuz.ReadOnly = false;
            this.tb_vuz.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tb_vuz.SelectedText = "";
            this.tb_vuz.SelectionLength = 0;
            this.tb_vuz.SelectionStart = 0;
            this.tb_vuz.ShortcutsEnabled = true;
            this.tb_vuz.Size = new System.Drawing.Size(540, 42);
            this.tb_vuz.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tb_vuz.TabIndex = 13;
            this.tb_vuz.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tb_vuz.TextMarginBottom = 0;
            this.tb_vuz.TextMarginLeft = 3;
            this.tb_vuz.TextMarginTop = 0;
            this.tb_vuz.TextPlaceholder = "Введите послевузовское профессиональное образование";
            this.tb_vuz.UseSystemPasswordChar = false;
            this.tb_vuz.WordWrap = true;
            // 
            // tb_kvalifikaziya2
            // 
            this.tb_kvalifikaziya2.AcceptsReturn = false;
            this.tb_kvalifikaziya2.AcceptsTab = false;
            this.tb_kvalifikaziya2.AnimationSpeed = 200;
            this.tb_kvalifikaziya2.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tb_kvalifikaziya2.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tb_kvalifikaziya2.BackColor = System.Drawing.Color.Transparent;
            this.tb_kvalifikaziya2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tb_kvalifikaziya2.BackgroundImage")));
            this.tb_kvalifikaziya2.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tb_kvalifikaziya2.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tb_kvalifikaziya2.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tb_kvalifikaziya2.BorderColorIdle = System.Drawing.Color.Silver;
            this.tb_kvalifikaziya2.BorderRadius = 40;
            this.tb_kvalifikaziya2.BorderThickness = 1;
            this.tb_kvalifikaziya2.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tb_kvalifikaziya2.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_kvalifikaziya2.DefaultFont = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Italic);
            this.tb_kvalifikaziya2.DefaultText = "";
            this.tb_kvalifikaziya2.FillColor = System.Drawing.Color.White;
            this.tb_kvalifikaziya2.HideSelection = true;
            this.tb_kvalifikaziya2.IconLeft = null;
            this.tb_kvalifikaziya2.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_kvalifikaziya2.IconPadding = 10;
            this.tb_kvalifikaziya2.IconRight = null;
            this.tb_kvalifikaziya2.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_kvalifikaziya2.Lines = new string[0];
            this.tb_kvalifikaziya2.Location = new System.Drawing.Point(549, 360);
            this.tb_kvalifikaziya2.MaxLength = 32767;
            this.tb_kvalifikaziya2.MinimumSize = new System.Drawing.Size(1, 1);
            this.tb_kvalifikaziya2.Modified = false;
            this.tb_kvalifikaziya2.Multiline = false;
            this.tb_kvalifikaziya2.Name = "tb_kvalifikaziya2";
            stateProperties21.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_kvalifikaziya2.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tb_kvalifikaziya2.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_kvalifikaziya2.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.Silver;
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.Empty;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_kvalifikaziya2.OnIdleState = stateProperties24;
            this.tb_kvalifikaziya2.Padding = new System.Windows.Forms.Padding(3);
            this.tb_kvalifikaziya2.PasswordChar = '\0';
            this.tb_kvalifikaziya2.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tb_kvalifikaziya2.PlaceholderText = "Введите квалификацию по документу учерждения";
            this.tb_kvalifikaziya2.ReadOnly = false;
            this.tb_kvalifikaziya2.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tb_kvalifikaziya2.SelectedText = "";
            this.tb_kvalifikaziya2.SelectionLength = 0;
            this.tb_kvalifikaziya2.SelectionStart = 0;
            this.tb_kvalifikaziya2.ShortcutsEnabled = true;
            this.tb_kvalifikaziya2.Size = new System.Drawing.Size(540, 42);
            this.tb_kvalifikaziya2.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tb_kvalifikaziya2.TabIndex = 12;
            this.tb_kvalifikaziya2.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tb_kvalifikaziya2.TextMarginBottom = 0;
            this.tb_kvalifikaziya2.TextMarginLeft = 3;
            this.tb_kvalifikaziya2.TextMarginTop = 0;
            this.tb_kvalifikaziya2.TextPlaceholder = "Введите квалификацию по документу учерждения";
            this.tb_kvalifikaziya2.UseSystemPasswordChar = false;
            this.tb_kvalifikaziya2.WordWrap = true;
            // 
            // tb_professiaDrugaya
            // 
            this.tb_professiaDrugaya.AcceptsReturn = false;
            this.tb_professiaDrugaya.AcceptsTab = false;
            this.tb_professiaDrugaya.AnimationSpeed = 200;
            this.tb_professiaDrugaya.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tb_professiaDrugaya.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tb_professiaDrugaya.BackColor = System.Drawing.Color.Transparent;
            this.tb_professiaDrugaya.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tb_professiaDrugaya.BackgroundImage")));
            this.tb_professiaDrugaya.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tb_professiaDrugaya.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tb_professiaDrugaya.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tb_professiaDrugaya.BorderColorIdle = System.Drawing.Color.Silver;
            this.tb_professiaDrugaya.BorderRadius = 40;
            this.tb_professiaDrugaya.BorderThickness = 1;
            this.tb_professiaDrugaya.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tb_professiaDrugaya.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_professiaDrugaya.DefaultFont = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Italic);
            this.tb_professiaDrugaya.DefaultText = "";
            this.tb_professiaDrugaya.FillColor = System.Drawing.Color.White;
            this.tb_professiaDrugaya.HideSelection = true;
            this.tb_professiaDrugaya.IconLeft = null;
            this.tb_professiaDrugaya.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_professiaDrugaya.IconPadding = 10;
            this.tb_professiaDrugaya.IconRight = null;
            this.tb_professiaDrugaya.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_professiaDrugaya.Lines = new string[0];
            this.tb_professiaDrugaya.Location = new System.Drawing.Point(549, 504);
            this.tb_professiaDrugaya.MaxLength = 32767;
            this.tb_professiaDrugaya.MinimumSize = new System.Drawing.Size(1, 1);
            this.tb_professiaDrugaya.Modified = false;
            this.tb_professiaDrugaya.Multiline = false;
            this.tb_professiaDrugaya.Name = "tb_professiaDrugaya";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_professiaDrugaya.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tb_professiaDrugaya.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_professiaDrugaya.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_professiaDrugaya.OnIdleState = stateProperties4;
            this.tb_professiaDrugaya.Padding = new System.Windows.Forms.Padding(3);
            this.tb_professiaDrugaya.PasswordChar = '\0';
            this.tb_professiaDrugaya.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tb_professiaDrugaya.PlaceholderText = "Введите профессию(доп)";
            this.tb_professiaDrugaya.ReadOnly = false;
            this.tb_professiaDrugaya.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tb_professiaDrugaya.SelectedText = "";
            this.tb_professiaDrugaya.SelectionLength = 0;
            this.tb_professiaDrugaya.SelectionStart = 0;
            this.tb_professiaDrugaya.ShortcutsEnabled = true;
            this.tb_professiaDrugaya.Size = new System.Drawing.Size(540, 42);
            this.tb_professiaDrugaya.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tb_professiaDrugaya.TabIndex = 17;
            this.tb_professiaDrugaya.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tb_professiaDrugaya.TextMarginBottom = 0;
            this.tb_professiaDrugaya.TextMarginLeft = 3;
            this.tb_professiaDrugaya.TextMarginTop = 0;
            this.tb_professiaDrugaya.TextPlaceholder = "Введите профессию(доп)";
            this.tb_professiaDrugaya.UseSystemPasswordChar = false;
            this.tb_professiaDrugaya.WordWrap = true;
            // 
            // tb_professiyaOsnovnaya
            // 
            this.tb_professiyaOsnovnaya.AcceptsReturn = false;
            this.tb_professiyaOsnovnaya.AcceptsTab = false;
            this.tb_professiyaOsnovnaya.AnimationSpeed = 200;
            this.tb_professiyaOsnovnaya.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tb_professiyaOsnovnaya.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tb_professiyaOsnovnaya.BackColor = System.Drawing.Color.Transparent;
            this.tb_professiyaOsnovnaya.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tb_professiyaOsnovnaya.BackgroundImage")));
            this.tb_professiyaOsnovnaya.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tb_professiyaOsnovnaya.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tb_professiyaOsnovnaya.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tb_professiyaOsnovnaya.BorderColorIdle = System.Drawing.Color.Silver;
            this.tb_professiyaOsnovnaya.BorderRadius = 40;
            this.tb_professiyaOsnovnaya.BorderThickness = 1;
            this.tb_professiyaOsnovnaya.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tb_professiyaOsnovnaya.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_professiyaOsnovnaya.DefaultFont = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Italic);
            this.tb_professiyaOsnovnaya.DefaultText = "";
            this.tb_professiyaOsnovnaya.FillColor = System.Drawing.Color.White;
            this.tb_professiyaOsnovnaya.HideSelection = true;
            this.tb_professiyaOsnovnaya.IconLeft = null;
            this.tb_professiyaOsnovnaya.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_professiyaOsnovnaya.IconPadding = 10;
            this.tb_professiyaOsnovnaya.IconRight = null;
            this.tb_professiyaOsnovnaya.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_professiyaOsnovnaya.Lines = new string[0];
            this.tb_professiyaOsnovnaya.Location = new System.Drawing.Point(552, 456);
            this.tb_professiyaOsnovnaya.MaxLength = 32767;
            this.tb_professiyaOsnovnaya.MinimumSize = new System.Drawing.Size(1, 1);
            this.tb_professiyaOsnovnaya.Modified = false;
            this.tb_professiyaOsnovnaya.Multiline = false;
            this.tb_professiyaOsnovnaya.Name = "tb_professiyaOsnovnaya";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_professiyaOsnovnaya.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tb_professiyaOsnovnaya.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_professiyaOsnovnaya.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_professiyaOsnovnaya.OnIdleState = stateProperties8;
            this.tb_professiyaOsnovnaya.Padding = new System.Windows.Forms.Padding(3);
            this.tb_professiyaOsnovnaya.PasswordChar = '\0';
            this.tb_professiyaOsnovnaya.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tb_professiyaOsnovnaya.PlaceholderText = "Введите профессию(основную)";
            this.tb_professiyaOsnovnaya.ReadOnly = false;
            this.tb_professiyaOsnovnaya.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tb_professiyaOsnovnaya.SelectedText = "";
            this.tb_professiyaOsnovnaya.SelectionLength = 0;
            this.tb_professiyaOsnovnaya.SelectionStart = 0;
            this.tb_professiyaOsnovnaya.ShortcutsEnabled = true;
            this.tb_professiyaOsnovnaya.Size = new System.Drawing.Size(540, 42);
            this.tb_professiyaOsnovnaya.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tb_professiyaOsnovnaya.TabIndex = 16;
            this.tb_professiyaOsnovnaya.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tb_professiyaOsnovnaya.TextMarginBottom = 0;
            this.tb_professiyaOsnovnaya.TextMarginLeft = 3;
            this.tb_professiyaOsnovnaya.TextMarginTop = 0;
            this.tb_professiyaOsnovnaya.TextPlaceholder = "Введите профессию(основную)";
            this.tb_professiyaOsnovnaya.UseSystemPasswordChar = false;
            this.tb_professiyaOsnovnaya.WordWrap = true;
            // 
            // tb_nazvanieUchrejdenia2
            // 
            this.tb_nazvanieUchrejdenia2.AcceptsReturn = false;
            this.tb_nazvanieUchrejdenia2.AcceptsTab = false;
            this.tb_nazvanieUchrejdenia2.AnimationSpeed = 200;
            this.tb_nazvanieUchrejdenia2.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tb_nazvanieUchrejdenia2.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tb_nazvanieUchrejdenia2.BackColor = System.Drawing.Color.Transparent;
            this.tb_nazvanieUchrejdenia2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tb_nazvanieUchrejdenia2.BackgroundImage")));
            this.tb_nazvanieUchrejdenia2.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tb_nazvanieUchrejdenia2.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tb_nazvanieUchrejdenia2.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tb_nazvanieUchrejdenia2.BorderColorIdle = System.Drawing.Color.Silver;
            this.tb_nazvanieUchrejdenia2.BorderRadius = 40;
            this.tb_nazvanieUchrejdenia2.BorderThickness = 1;
            this.tb_nazvanieUchrejdenia2.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tb_nazvanieUchrejdenia2.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_nazvanieUchrejdenia2.DefaultFont = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Italic);
            this.tb_nazvanieUchrejdenia2.DefaultText = "";
            this.tb_nazvanieUchrejdenia2.FillColor = System.Drawing.Color.White;
            this.tb_nazvanieUchrejdenia2.HideSelection = true;
            this.tb_nazvanieUchrejdenia2.IconLeft = null;
            this.tb_nazvanieUchrejdenia2.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_nazvanieUchrejdenia2.IconPadding = 10;
            this.tb_nazvanieUchrejdenia2.IconRight = null;
            this.tb_nazvanieUchrejdenia2.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_nazvanieUchrejdenia2.Lines = new string[0];
            this.tb_nazvanieUchrejdenia2.Location = new System.Drawing.Point(3, 504);
            this.tb_nazvanieUchrejdenia2.MaxLength = 32767;
            this.tb_nazvanieUchrejdenia2.MinimumSize = new System.Drawing.Size(1, 1);
            this.tb_nazvanieUchrejdenia2.Modified = false;
            this.tb_nazvanieUchrejdenia2.Multiline = false;
            this.tb_nazvanieUchrejdenia2.Name = "tb_nazvanieUchrejdenia2";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_nazvanieUchrejdenia2.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tb_nazvanieUchrejdenia2.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_nazvanieUchrejdenia2.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_nazvanieUchrejdenia2.OnIdleState = stateProperties12;
            this.tb_nazvanieUchrejdenia2.Padding = new System.Windows.Forms.Padding(3);
            this.tb_nazvanieUchrejdenia2.PasswordChar = '\0';
            this.tb_nazvanieUchrejdenia2.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tb_nazvanieUchrejdenia2.PlaceholderText = "Введите второе наименование оброзовательного учереждения";
            this.tb_nazvanieUchrejdenia2.ReadOnly = false;
            this.tb_nazvanieUchrejdenia2.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tb_nazvanieUchrejdenia2.SelectedText = "";
            this.tb_nazvanieUchrejdenia2.SelectionLength = 0;
            this.tb_nazvanieUchrejdenia2.SelectionStart = 0;
            this.tb_nazvanieUchrejdenia2.ShortcutsEnabled = true;
            this.tb_nazvanieUchrejdenia2.Size = new System.Drawing.Size(540, 42);
            this.tb_nazvanieUchrejdenia2.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tb_nazvanieUchrejdenia2.TabIndex = 15;
            this.tb_nazvanieUchrejdenia2.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tb_nazvanieUchrejdenia2.TextMarginBottom = 0;
            this.tb_nazvanieUchrejdenia2.TextMarginLeft = 3;
            this.tb_nazvanieUchrejdenia2.TextMarginTop = 0;
            this.tb_nazvanieUchrejdenia2.TextPlaceholder = "Введите второе наименование оброзовательного учереждения";
            this.tb_nazvanieUchrejdenia2.UseSystemPasswordChar = false;
            this.tb_nazvanieUchrejdenia2.WordWrap = true;
            // 
            // tb_kvalifikaziya
            // 
            this.tb_kvalifikaziya.AcceptsReturn = false;
            this.tb_kvalifikaziya.AcceptsTab = false;
            this.tb_kvalifikaziya.AnimationSpeed = 200;
            this.tb_kvalifikaziya.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tb_kvalifikaziya.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tb_kvalifikaziya.BackColor = System.Drawing.Color.Transparent;
            this.tb_kvalifikaziya.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tb_kvalifikaziya.BackgroundImage")));
            this.tb_kvalifikaziya.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tb_kvalifikaziya.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tb_kvalifikaziya.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tb_kvalifikaziya.BorderColorIdle = System.Drawing.Color.Silver;
            this.tb_kvalifikaziya.BorderRadius = 40;
            this.tb_kvalifikaziya.BorderThickness = 1;
            this.tb_kvalifikaziya.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tb_kvalifikaziya.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_kvalifikaziya.DefaultFont = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Italic);
            this.tb_kvalifikaziya.DefaultText = "";
            this.tb_kvalifikaziya.FillColor = System.Drawing.Color.White;
            this.tb_kvalifikaziya.HideSelection = true;
            this.tb_kvalifikaziya.IconLeft = null;
            this.tb_kvalifikaziya.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_kvalifikaziya.IconPadding = 10;
            this.tb_kvalifikaziya.IconRight = null;
            this.tb_kvalifikaziya.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_kvalifikaziya.Lines = new string[0];
            this.tb_kvalifikaziya.Location = new System.Drawing.Point(3, 456);
            this.tb_kvalifikaziya.MaxLength = 32767;
            this.tb_kvalifikaziya.MinimumSize = new System.Drawing.Size(1, 1);
            this.tb_kvalifikaziya.Modified = false;
            this.tb_kvalifikaziya.Multiline = false;
            this.tb_kvalifikaziya.Name = "tb_kvalifikaziya";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_kvalifikaziya.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tb_kvalifikaziya.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_kvalifikaziya.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_kvalifikaziya.OnIdleState = stateProperties16;
            this.tb_kvalifikaziya.Padding = new System.Windows.Forms.Padding(3);
            this.tb_kvalifikaziya.PasswordChar = '\0';
            this.tb_kvalifikaziya.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tb_kvalifikaziya.PlaceholderText = "Введите квалификацию по документу учерждения";
            this.tb_kvalifikaziya.ReadOnly = false;
            this.tb_kvalifikaziya.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tb_kvalifikaziya.SelectedText = "";
            this.tb_kvalifikaziya.SelectionLength = 0;
            this.tb_kvalifikaziya.SelectionStart = 0;
            this.tb_kvalifikaziya.ShortcutsEnabled = true;
            this.tb_kvalifikaziya.Size = new System.Drawing.Size(540, 42);
            this.tb_kvalifikaziya.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tb_kvalifikaziya.TabIndex = 14;
            this.tb_kvalifikaziya.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tb_kvalifikaziya.TextMarginBottom = 0;
            this.tb_kvalifikaziya.TextMarginLeft = 3;
            this.tb_kvalifikaziya.TextMarginTop = 0;
            this.tb_kvalifikaziya.TextPlaceholder = "Введите квалификацию по документу учерждения";
            this.tb_kvalifikaziya.UseSystemPasswordChar = false;
            this.tb_kvalifikaziya.WordWrap = true;
            // 
            // tb_exit
            // 
            this.tb_exit.AllowAnimations = true;
            this.tb_exit.AllowMouseEffects = true;
            this.tb_exit.AllowToggling = false;
            this.tb_exit.AnimationSpeed = 200;
            this.tb_exit.AutoGenerateColors = false;
            this.tb_exit.AutoRoundBorders = false;
            this.tb_exit.AutoSizeLeftIcon = true;
            this.tb_exit.AutoSizeRightIcon = true;
            this.tb_exit.BackColor = System.Drawing.Color.Transparent;
            this.tb_exit.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(41)))));
            this.tb_exit.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tb_exit.BackgroundImage")));
            this.tb_exit.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.tb_exit.ButtonText = "Выйти";
            this.tb_exit.ButtonTextMarginLeft = 0;
            this.tb_exit.ColorContrastOnClick = 45;
            this.tb_exit.ColorContrastOnHover = 45;
            this.tb_exit.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.tb_exit.CustomizableEdges = borderEdges1;
            this.tb_exit.DialogResult = System.Windows.Forms.DialogResult.None;
            this.tb_exit.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.tb_exit.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tb_exit.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.tb_exit.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.tb_exit.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Italic);
            this.tb_exit.ForeColor = System.Drawing.Color.White;
            this.tb_exit.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.tb_exit.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.tb_exit.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.tb_exit.IconMarginLeft = 11;
            this.tb_exit.IconPadding = 10;
            this.tb_exit.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.tb_exit.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.tb_exit.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.tb_exit.IconSize = 25;
            this.tb_exit.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(41)))));
            this.tb_exit.IdleBorderRadius = 40;
            this.tb_exit.IdleBorderThickness = 1;
            this.tb_exit.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(41)))));
            this.tb_exit.IdleIconLeftImage = null;
            this.tb_exit.IdleIconRightImage = null;
            this.tb_exit.IndicateFocus = false;
            this.tb_exit.Location = new System.Drawing.Point(1155, 518);
            this.tb_exit.Name = "tb_exit";
            this.tb_exit.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.tb_exit.OnDisabledState.BorderRadius = 40;
            this.tb_exit.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.tb_exit.OnDisabledState.BorderThickness = 1;
            this.tb_exit.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tb_exit.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.tb_exit.OnDisabledState.IconLeftImage = null;
            this.tb_exit.OnDisabledState.IconRightImage = null;
            this.tb_exit.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tb_exit.onHoverState.BorderRadius = 40;
            this.tb_exit.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.tb_exit.onHoverState.BorderThickness = 1;
            this.tb_exit.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tb_exit.onHoverState.ForeColor = System.Drawing.Color.White;
            this.tb_exit.onHoverState.IconLeftImage = null;
            this.tb_exit.onHoverState.IconRightImage = null;
            this.tb_exit.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(41)))));
            this.tb_exit.OnIdleState.BorderRadius = 40;
            this.tb_exit.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.tb_exit.OnIdleState.BorderThickness = 1;
            this.tb_exit.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(41)))));
            this.tb_exit.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.tb_exit.OnIdleState.IconLeftImage = null;
            this.tb_exit.OnIdleState.IconRightImage = null;
            this.tb_exit.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.tb_exit.OnPressedState.BorderRadius = 40;
            this.tb_exit.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.tb_exit.OnPressedState.BorderThickness = 1;
            this.tb_exit.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.tb_exit.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.tb_exit.OnPressedState.IconLeftImage = null;
            this.tb_exit.OnPressedState.IconRightImage = null;
            this.tb_exit.Size = new System.Drawing.Size(242, 49);
            this.tb_exit.TabIndex = 22;
            this.tb_exit.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.tb_exit.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.tb_exit.TextMarginLeft = 0;
            this.tb_exit.TextPadding = new System.Windows.Forms.Padding(0);
            this.tb_exit.UseDefaultRadiusAndThickness = true;
            // 
            // btn_del
            // 
            this.btn_del.AllowAnimations = true;
            this.btn_del.AllowMouseEffects = true;
            this.btn_del.AllowToggling = false;
            this.btn_del.AnimationSpeed = 200;
            this.btn_del.AutoGenerateColors = false;
            this.btn_del.AutoRoundBorders = false;
            this.btn_del.AutoSizeLeftIcon = true;
            this.btn_del.AutoSizeRightIcon = true;
            this.btn_del.BackColor = System.Drawing.Color.Transparent;
            this.btn_del.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(41)))));
            this.btn_del.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_del.BackgroundImage")));
            this.btn_del.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_del.ButtonText = "Удалить";
            this.btn_del.ButtonTextMarginLeft = 0;
            this.btn_del.ColorContrastOnClick = 45;
            this.btn_del.ColorContrastOnHover = 45;
            this.btn_del.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btn_del.CustomizableEdges = borderEdges2;
            this.btn_del.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_del.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_del.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_del.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_del.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btn_del.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Italic);
            this.btn_del.ForeColor = System.Drawing.Color.White;
            this.btn_del.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_del.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn_del.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btn_del.IconMarginLeft = 11;
            this.btn_del.IconPadding = 10;
            this.btn_del.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn_del.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn_del.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn_del.IconSize = 25;
            this.btn_del.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(41)))));
            this.btn_del.IdleBorderRadius = 40;
            this.btn_del.IdleBorderThickness = 1;
            this.btn_del.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(41)))));
            this.btn_del.IdleIconLeftImage = null;
            this.btn_del.IdleIconRightImage = null;
            this.btn_del.IndicateFocus = false;
            this.btn_del.Location = new System.Drawing.Point(1155, 463);
            this.btn_del.Name = "btn_del";
            this.btn_del.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_del.OnDisabledState.BorderRadius = 40;
            this.btn_del.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_del.OnDisabledState.BorderThickness = 1;
            this.btn_del.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_del.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_del.OnDisabledState.IconLeftImage = null;
            this.btn_del.OnDisabledState.IconRightImage = null;
            this.btn_del.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btn_del.onHoverState.BorderRadius = 40;
            this.btn_del.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_del.onHoverState.BorderThickness = 1;
            this.btn_del.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btn_del.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btn_del.onHoverState.IconLeftImage = null;
            this.btn_del.onHoverState.IconRightImage = null;
            this.btn_del.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(41)))));
            this.btn_del.OnIdleState.BorderRadius = 40;
            this.btn_del.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_del.OnIdleState.BorderThickness = 1;
            this.btn_del.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(41)))));
            this.btn_del.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btn_del.OnIdleState.IconLeftImage = null;
            this.btn_del.OnIdleState.IconRightImage = null;
            this.btn_del.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_del.OnPressedState.BorderRadius = 40;
            this.btn_del.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_del.OnPressedState.BorderThickness = 1;
            this.btn_del.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_del.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btn_del.OnPressedState.IconLeftImage = null;
            this.btn_del.OnPressedState.IconRightImage = null;
            this.btn_del.Size = new System.Drawing.Size(242, 49);
            this.btn_del.TabIndex = 21;
            this.btn_del.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_del.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn_del.TextMarginLeft = 0;
            this.btn_del.TextPadding = new System.Windows.Forms.Padding(0);
            this.btn_del.UseDefaultRadiusAndThickness = true;
            // 
            // btn_upd
            // 
            this.btn_upd.AllowAnimations = true;
            this.btn_upd.AllowMouseEffects = true;
            this.btn_upd.AllowToggling = false;
            this.btn_upd.AnimationSpeed = 200;
            this.btn_upd.AutoGenerateColors = false;
            this.btn_upd.AutoRoundBorders = false;
            this.btn_upd.AutoSizeLeftIcon = true;
            this.btn_upd.AutoSizeRightIcon = true;
            this.btn_upd.BackColor = System.Drawing.Color.Transparent;
            this.btn_upd.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(41)))));
            this.btn_upd.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_upd.BackgroundImage")));
            this.btn_upd.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_upd.ButtonText = "Изменить";
            this.btn_upd.ButtonTextMarginLeft = 0;
            this.btn_upd.ColorContrastOnClick = 45;
            this.btn_upd.ColorContrastOnHover = 45;
            this.btn_upd.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.btn_upd.CustomizableEdges = borderEdges3;
            this.btn_upd.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_upd.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_upd.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_upd.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_upd.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btn_upd.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Italic);
            this.btn_upd.ForeColor = System.Drawing.Color.White;
            this.btn_upd.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_upd.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn_upd.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btn_upd.IconMarginLeft = 11;
            this.btn_upd.IconPadding = 10;
            this.btn_upd.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn_upd.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn_upd.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn_upd.IconSize = 25;
            this.btn_upd.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(41)))));
            this.btn_upd.IdleBorderRadius = 40;
            this.btn_upd.IdleBorderThickness = 1;
            this.btn_upd.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(41)))));
            this.btn_upd.IdleIconLeftImage = null;
            this.btn_upd.IdleIconRightImage = null;
            this.btn_upd.IndicateFocus = false;
            this.btn_upd.Location = new System.Drawing.Point(1155, 408);
            this.btn_upd.Name = "btn_upd";
            this.btn_upd.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_upd.OnDisabledState.BorderRadius = 40;
            this.btn_upd.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_upd.OnDisabledState.BorderThickness = 1;
            this.btn_upd.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_upd.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_upd.OnDisabledState.IconLeftImage = null;
            this.btn_upd.OnDisabledState.IconRightImage = null;
            this.btn_upd.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btn_upd.onHoverState.BorderRadius = 40;
            this.btn_upd.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_upd.onHoverState.BorderThickness = 1;
            this.btn_upd.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btn_upd.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btn_upd.onHoverState.IconLeftImage = null;
            this.btn_upd.onHoverState.IconRightImage = null;
            this.btn_upd.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(41)))));
            this.btn_upd.OnIdleState.BorderRadius = 40;
            this.btn_upd.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_upd.OnIdleState.BorderThickness = 1;
            this.btn_upd.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(41)))));
            this.btn_upd.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btn_upd.OnIdleState.IconLeftImage = null;
            this.btn_upd.OnIdleState.IconRightImage = null;
            this.btn_upd.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_upd.OnPressedState.BorderRadius = 40;
            this.btn_upd.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_upd.OnPressedState.BorderThickness = 1;
            this.btn_upd.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_upd.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btn_upd.OnPressedState.IconLeftImage = null;
            this.btn_upd.OnPressedState.IconRightImage = null;
            this.btn_upd.Size = new System.Drawing.Size(242, 49);
            this.btn_upd.TabIndex = 20;
            this.btn_upd.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_upd.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn_upd.TextMarginLeft = 0;
            this.btn_upd.TextPadding = new System.Windows.Forms.Padding(0);
            this.btn_upd.UseDefaultRadiusAndThickness = true;
            // 
            // btn_add
            // 
            this.btn_add.AllowAnimations = true;
            this.btn_add.AllowMouseEffects = true;
            this.btn_add.AllowToggling = false;
            this.btn_add.AnimationSpeed = 200;
            this.btn_add.AutoGenerateColors = false;
            this.btn_add.AutoRoundBorders = false;
            this.btn_add.AutoSizeLeftIcon = true;
            this.btn_add.AutoSizeRightIcon = true;
            this.btn_add.BackColor = System.Drawing.Color.Transparent;
            this.btn_add.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(41)))));
            this.btn_add.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_add.BackgroundImage")));
            this.btn_add.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_add.ButtonText = "Добавить";
            this.btn_add.ButtonTextMarginLeft = 0;
            this.btn_add.ColorContrastOnClick = 45;
            this.btn_add.ColorContrastOnHover = 45;
            this.btn_add.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.btn_add.CustomizableEdges = borderEdges4;
            this.btn_add.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_add.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_add.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_add.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_add.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btn_add.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Italic);
            this.btn_add.ForeColor = System.Drawing.Color.White;
            this.btn_add.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_add.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn_add.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btn_add.IconMarginLeft = 11;
            this.btn_add.IconPadding = 10;
            this.btn_add.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn_add.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn_add.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn_add.IconSize = 25;
            this.btn_add.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(41)))));
            this.btn_add.IdleBorderRadius = 40;
            this.btn_add.IdleBorderThickness = 1;
            this.btn_add.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(41)))));
            this.btn_add.IdleIconLeftImage = null;
            this.btn_add.IdleIconRightImage = null;
            this.btn_add.IndicateFocus = false;
            this.btn_add.Location = new System.Drawing.Point(1155, 353);
            this.btn_add.Name = "btn_add";
            this.btn_add.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_add.OnDisabledState.BorderRadius = 40;
            this.btn_add.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_add.OnDisabledState.BorderThickness = 1;
            this.btn_add.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_add.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_add.OnDisabledState.IconLeftImage = null;
            this.btn_add.OnDisabledState.IconRightImage = null;
            this.btn_add.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btn_add.onHoverState.BorderRadius = 40;
            this.btn_add.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_add.onHoverState.BorderThickness = 1;
            this.btn_add.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btn_add.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btn_add.onHoverState.IconLeftImage = null;
            this.btn_add.onHoverState.IconRightImage = null;
            this.btn_add.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(41)))));
            this.btn_add.OnIdleState.BorderRadius = 40;
            this.btn_add.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_add.OnIdleState.BorderThickness = 1;
            this.btn_add.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(41)))));
            this.btn_add.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btn_add.OnIdleState.IconLeftImage = null;
            this.btn_add.OnIdleState.IconRightImage = null;
            this.btn_add.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_add.OnPressedState.BorderRadius = 40;
            this.btn_add.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_add.OnPressedState.BorderThickness = 1;
            this.btn_add.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_add.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btn_add.OnPressedState.IconLeftImage = null;
            this.btn_add.OnPressedState.IconRightImage = null;
            this.btn_add.Size = new System.Drawing.Size(242, 49);
            this.btn_add.TabIndex = 19;
            this.btn_add.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_add.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn_add.TextMarginLeft = 0;
            this.btn_add.TextPadding = new System.Windows.Forms.Padding(0);
            this.btn_add.UseDefaultRadiusAndThickness = true;
            // 
            // groupBox1
            // 
            this.groupBox1.AllowParentOverrides = false;
            this.groupBox1.AutoEllipsis = false;
            this.groupBox1.CursorType = null;
            this.groupBox1.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Italic);
            this.groupBox1.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(41)))));
            this.groupBox1.Location = new System.Drawing.Point(16, 335);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.groupBox1.Size = new System.Drawing.Size(0, 0);
            this.groupBox1.TabIndex = 23;
            this.groupBox1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.groupBox1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // InformationObrozovaniySotrudnik
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(41)))));
            this.ClientSize = new System.Drawing.Size(1512, 683);
            this.Controls.Add(this.bunifuPanel1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "InformationObrozovaniySotrudnik";
            this.Text = "СИБИРЬ";
            this.Load += new System.EventHandler(this.ObrazovanieForm_Load);
            this.bunifuPanel1.ResumeLayout(false);
            this.bunifuPanel1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.DGV_Obrazovanie)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.Framework.UI.BunifuElipse bunifuElipse1;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel1;
        private Bunifu.UI.WinForms.BunifuDataGridView DGV_Obrazovanie;
        private Bunifu.UI.WinForms.BunifuTextBox tb_vuz;
        private Bunifu.UI.WinForms.BunifuTextBox tb_kvalifikaziya2;
        private Bunifu.UI.WinForms.BunifuTextBox tb_nazvanieUchrejdenia;
        private Bunifu.UI.WinForms.BunifuTextBox tb_obrazovanie;
        private Bunifu.UI.WinForms.BunifuTextBox tb_professiaDrugaya;
        private Bunifu.UI.WinForms.BunifuTextBox tb_professiyaOsnovnaya;
        private Bunifu.UI.WinForms.BunifuTextBox tb_nazvanieUchrejdenia2;
        private Bunifu.UI.WinForms.BunifuTextBox tb_kvalifikaziya;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton tb_exit;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_del;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_upd;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_add;
        private Bunifu.UI.WinForms.BunifuLabel groupBox1;
    }
}