
namespace Examen.Main
{
    partial class Registration
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Registration));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties29 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties30 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties31 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties32 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.bunifuElipse1 = new Bunifu.Framework.UI.BunifuElipse(this.components);
            this.bunifuPictureBox3 = new Bunifu.UI.WinForms.BunifuPictureBox();
            this.bunifuPanel2 = new Bunifu.UI.WinForms.BunifuPanel();
            this.bunifuLabel3 = new Bunifu.UI.WinForms.BunifuLabel();
            this.tb_pass2 = new Bunifu.UI.WinForms.BunifuTextBox();
            this.tb_logim = new Bunifu.UI.WinForms.BunifuTextBox();
            this.tb_pass = new Bunifu.UI.WinForms.BunifuTextBox();
            this.yt_Button1 = new Bunifu.UI.WinForms.BunifuPanel();
            this.bunifuLabel2 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuButton1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.pictureBox1 = new Bunifu.UI.WinForms.BunifuPictureBox();
            this.bunifuPanel1 = new Bunifu.UI.WinForms.BunifuPanel();
            this.btn_autorization = new Bunifu.UI.WinForms.BunifuLabel();
            this.btn_reg = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.tb_tel = new Bunifu.UI.WinForms.BunifuTextBox();
            this.tb_dol = new Bunifu.UI.WinForms.BunifuTextBox();
            this.tb_patronomic = new Bunifu.UI.WinForms.BunifuTextBox();
            this.tb_fam = new Bunifu.UI.WinForms.BunifuTextBox();
            this.tb_nam = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox3)).BeginInit();
            this.bunifuPanel2.SuspendLayout();
            this.yt_Button1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).BeginInit();
            this.bunifuPanel1.SuspendLayout();
            this.SuspendLayout();
            // 
            // bunifuElipse1
            // 
            this.bunifuElipse1.ElipseRadius = 40;
            this.bunifuElipse1.TargetControl = this;
            // 
            // bunifuPictureBox3
            // 
            this.bunifuPictureBox3.AllowFocused = false;
            this.bunifuPictureBox3.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.bunifuPictureBox3.AutoSizeHeight = true;
            this.bunifuPictureBox3.BorderRadius = 17;
            this.bunifuPictureBox3.Image = global::Examen.Properties.Resources._1486564399_close_815123;
            this.bunifuPictureBox3.IsCircle = true;
            this.bunifuPictureBox3.Location = new System.Drawing.Point(1243, 12);
            this.bunifuPictureBox3.Name = "bunifuPictureBox3";
            this.bunifuPictureBox3.Size = new System.Drawing.Size(34, 34);
            this.bunifuPictureBox3.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.bunifuPictureBox3.TabIndex = 17;
            this.bunifuPictureBox3.TabStop = false;
            this.bunifuPictureBox3.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Circle;
            this.bunifuPictureBox3.Click += new System.EventHandler(this.bunifuPictureBox3_Click);
            // 
            // bunifuPanel2
            // 
            this.bunifuPanel2.BackgroundColor = System.Drawing.Color.Snow;
            this.bunifuPanel2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel2.BackgroundImage")));
            this.bunifuPanel2.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel2.BorderColor = System.Drawing.Color.Snow;
            this.bunifuPanel2.BorderRadius = 40;
            this.bunifuPanel2.BorderThickness = 1;
            this.bunifuPanel2.Controls.Add(this.bunifuLabel3);
            this.bunifuPanel2.Controls.Add(this.tb_pass2);
            this.bunifuPanel2.Controls.Add(this.tb_logim);
            this.bunifuPanel2.Controls.Add(this.tb_pass);
            this.bunifuPanel2.Location = new System.Drawing.Point(786, 391);
            this.bunifuPanel2.Name = "bunifuPanel2";
            this.bunifuPanel2.ShowBorders = true;
            this.bunifuPanel2.Size = new System.Drawing.Size(426, 335);
            this.bunifuPanel2.TabIndex = 13;
            // 
            // bunifuLabel3
            // 
            this.bunifuLabel3.AllowParentOverrides = false;
            this.bunifuLabel3.AutoEllipsis = false;
            this.bunifuLabel3.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel3.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel3.Font = new System.Drawing.Font("Arial Rounded MT Bold", 20.25F);
            this.bunifuLabel3.Location = new System.Drawing.Point(48, 21);
            this.bunifuLabel3.Name = "bunifuLabel3";
            this.bunifuLabel3.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel3.Size = new System.Drawing.Size(339, 38);
            this.bunifuLabel3.TabIndex = 13;
            this.bunifuLabel3.Text = "Account information!";
            this.bunifuLabel3.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel3.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // tb_pass2
            // 
            this.tb_pass2.AcceptsReturn = false;
            this.tb_pass2.AcceptsTab = false;
            this.tb_pass2.AnimationSpeed = 200;
            this.tb_pass2.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tb_pass2.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tb_pass2.BackColor = System.Drawing.Color.Transparent;
            this.tb_pass2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tb_pass2.BackgroundImage")));
            this.tb_pass2.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tb_pass2.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tb_pass2.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tb_pass2.BorderColorIdle = System.Drawing.Color.Silver;
            this.tb_pass2.BorderRadius = 40;
            this.tb_pass2.BorderThickness = 1;
            this.tb_pass2.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tb_pass2.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_pass2.DefaultFont = new System.Drawing.Font("Segoe UI", 15F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.tb_pass2.DefaultText = "";
            this.tb_pass2.FillColor = System.Drawing.Color.White;
            this.tb_pass2.HideSelection = true;
            this.tb_pass2.IconLeft = null;
            this.tb_pass2.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_pass2.IconPadding = 10;
            this.tb_pass2.IconRight = null;
            this.tb_pass2.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_pass2.Lines = new string[0];
            this.tb_pass2.Location = new System.Drawing.Point(9, 223);
            this.tb_pass2.MaxLength = 32767;
            this.tb_pass2.MinimumSize = new System.Drawing.Size(1, 1);
            this.tb_pass2.Modified = false;
            this.tb_pass2.Multiline = false;
            this.tb_pass2.Name = "tb_pass2";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_pass2.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tb_pass2.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_pass2.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_pass2.OnIdleState = stateProperties4;
            this.tb_pass2.Padding = new System.Windows.Forms.Padding(3);
            this.tb_pass2.PasswordChar = '\0';
            this.tb_pass2.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tb_pass2.PlaceholderText = "Введите подверждение пароля";
            this.tb_pass2.ReadOnly = false;
            this.tb_pass2.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tb_pass2.SelectedText = "";
            this.tb_pass2.SelectionLength = 0;
            this.tb_pass2.SelectionStart = 0;
            this.tb_pass2.ShortcutsEnabled = true;
            this.tb_pass2.Size = new System.Drawing.Size(399, 47);
            this.tb_pass2.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tb_pass2.TabIndex = 8;
            this.tb_pass2.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.tb_pass2.TextMarginBottom = 0;
            this.tb_pass2.TextMarginLeft = 3;
            this.tb_pass2.TextMarginTop = 0;
            this.tb_pass2.TextPlaceholder = "Введите подверждение пароля";
            this.tb_pass2.UseSystemPasswordChar = false;
            this.tb_pass2.WordWrap = true;
            // 
            // tb_logim
            // 
            this.tb_logim.AcceptsReturn = false;
            this.tb_logim.AcceptsTab = false;
            this.tb_logim.AnimationSpeed = 200;
            this.tb_logim.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tb_logim.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tb_logim.BackColor = System.Drawing.Color.Transparent;
            this.tb_logim.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tb_logim.BackgroundImage")));
            this.tb_logim.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tb_logim.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tb_logim.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tb_logim.BorderColorIdle = System.Drawing.Color.Silver;
            this.tb_logim.BorderRadius = 40;
            this.tb_logim.BorderThickness = 1;
            this.tb_logim.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tb_logim.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_logim.DefaultFont = new System.Drawing.Font("Segoe UI", 15F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.tb_logim.DefaultText = "";
            this.tb_logim.FillColor = System.Drawing.Color.White;
            this.tb_logim.HideSelection = true;
            this.tb_logim.IconLeft = null;
            this.tb_logim.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_logim.IconPadding = 10;
            this.tb_logim.IconRight = null;
            this.tb_logim.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_logim.Lines = new string[0];
            this.tb_logim.Location = new System.Drawing.Point(9, 101);
            this.tb_logim.MaxLength = 32767;
            this.tb_logim.MinimumSize = new System.Drawing.Size(1, 1);
            this.tb_logim.Modified = false;
            this.tb_logim.Multiline = false;
            this.tb_logim.Name = "tb_logim";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_logim.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tb_logim.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_logim.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_logim.OnIdleState = stateProperties8;
            this.tb_logim.Padding = new System.Windows.Forms.Padding(3);
            this.tb_logim.PasswordChar = '\0';
            this.tb_logim.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tb_logim.PlaceholderText = "Введите логин";
            this.tb_logim.ReadOnly = false;
            this.tb_logim.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tb_logim.SelectedText = "";
            this.tb_logim.SelectionLength = 0;
            this.tb_logim.SelectionStart = 0;
            this.tb_logim.ShortcutsEnabled = true;
            this.tb_logim.Size = new System.Drawing.Size(399, 47);
            this.tb_logim.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tb_logim.TabIndex = 6;
            this.tb_logim.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.tb_logim.TextMarginBottom = 0;
            this.tb_logim.TextMarginLeft = 3;
            this.tb_logim.TextMarginTop = 0;
            this.tb_logim.TextPlaceholder = "Введите логин";
            this.tb_logim.UseSystemPasswordChar = false;
            this.tb_logim.WordWrap = true;
            // 
            // tb_pass
            // 
            this.tb_pass.AcceptsReturn = false;
            this.tb_pass.AcceptsTab = false;
            this.tb_pass.AnimationSpeed = 200;
            this.tb_pass.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tb_pass.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tb_pass.BackColor = System.Drawing.Color.Transparent;
            this.tb_pass.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tb_pass.BackgroundImage")));
            this.tb_pass.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tb_pass.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tb_pass.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tb_pass.BorderColorIdle = System.Drawing.Color.Silver;
            this.tb_pass.BorderRadius = 40;
            this.tb_pass.BorderThickness = 1;
            this.tb_pass.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tb_pass.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_pass.DefaultFont = new System.Drawing.Font("Segoe UI", 15F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.tb_pass.DefaultText = "";
            this.tb_pass.FillColor = System.Drawing.Color.White;
            this.tb_pass.HideSelection = true;
            this.tb_pass.IconLeft = null;
            this.tb_pass.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_pass.IconPadding = 10;
            this.tb_pass.IconRight = null;
            this.tb_pass.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_pass.Lines = new string[0];
            this.tb_pass.Location = new System.Drawing.Point(9, 163);
            this.tb_pass.MaxLength = 32767;
            this.tb_pass.MinimumSize = new System.Drawing.Size(1, 1);
            this.tb_pass.Modified = false;
            this.tb_pass.Multiline = false;
            this.tb_pass.Name = "tb_pass";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_pass.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tb_pass.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_pass.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_pass.OnIdleState = stateProperties12;
            this.tb_pass.Padding = new System.Windows.Forms.Padding(3);
            this.tb_pass.PasswordChar = '\0';
            this.tb_pass.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tb_pass.PlaceholderText = "Введите пароль";
            this.tb_pass.ReadOnly = false;
            this.tb_pass.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tb_pass.SelectedText = "";
            this.tb_pass.SelectionLength = 0;
            this.tb_pass.SelectionStart = 0;
            this.tb_pass.ShortcutsEnabled = true;
            this.tb_pass.Size = new System.Drawing.Size(399, 47);
            this.tb_pass.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tb_pass.TabIndex = 7;
            this.tb_pass.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.tb_pass.TextMarginBottom = 0;
            this.tb_pass.TextMarginLeft = 3;
            this.tb_pass.TextMarginTop = 0;
            this.tb_pass.TextPlaceholder = "Введите пароль";
            this.tb_pass.UseSystemPasswordChar = false;
            this.tb_pass.WordWrap = true;
            // 
            // yt_Button1
            // 
            this.yt_Button1.BackgroundColor = System.Drawing.Color.Snow;
            this.yt_Button1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("yt_Button1.BackgroundImage")));
            this.yt_Button1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.yt_Button1.BorderColor = System.Drawing.Color.Snow;
            this.yt_Button1.BorderRadius = 40;
            this.yt_Button1.BorderThickness = 1;
            this.yt_Button1.Controls.Add(this.bunifuLabel2);
            this.yt_Button1.Controls.Add(this.bunifuButton1);
            this.yt_Button1.Controls.Add(this.pictureBox1);
            this.yt_Button1.Location = new System.Drawing.Point(786, 50);
            this.yt_Button1.Name = "yt_Button1";
            this.yt_Button1.ShowBorders = true;
            this.yt_Button1.Size = new System.Drawing.Size(426, 335);
            this.yt_Button1.TabIndex = 1;
            // 
            // bunifuLabel2
            // 
            this.bunifuLabel2.AllowParentOverrides = false;
            this.bunifuLabel2.AutoEllipsis = false;
            this.bunifuLabel2.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel2.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel2.Font = new System.Drawing.Font("Arial Rounded MT Bold", 20.25F);
            this.bunifuLabel2.Location = new System.Drawing.Point(98, 25);
            this.bunifuLabel2.Name = "bunifuLabel2";
            this.bunifuLabel2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel2.Size = new System.Drawing.Size(239, 38);
            this.bunifuLabel2.TabIndex = 12;
            this.bunifuLabel2.Text = "Upload avatar!";
            this.bunifuLabel2.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel2.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuButton1
            // 
            this.bunifuButton1.AllowAnimations = true;
            this.bunifuButton1.AllowMouseEffects = true;
            this.bunifuButton1.AllowToggling = false;
            this.bunifuButton1.AnimationSpeed = 200;
            this.bunifuButton1.AutoGenerateColors = false;
            this.bunifuButton1.AutoRoundBorders = false;
            this.bunifuButton1.AutoSizeLeftIcon = true;
            this.bunifuButton1.AutoSizeRightIcon = true;
            this.bunifuButton1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton1.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(41)))));
            this.bunifuButton1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton1.BackgroundImage")));
            this.bunifuButton1.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.ButtonText = "SET AVATAR";
            this.bunifuButton1.ButtonTextMarginLeft = 0;
            this.bunifuButton1.ColorContrastOnClick = 45;
            this.bunifuButton1.ColorContrastOnHover = 45;
            this.bunifuButton1.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.bunifuButton1.CustomizableEdges = borderEdges1;
            this.bunifuButton1.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton1.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton1.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton1.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton1.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButton1.Font = new System.Drawing.Font("Segoe UI Semibold", 16F, System.Drawing.FontStyle.Bold);
            this.bunifuButton1.ForeColor = System.Drawing.Color.Snow;
            this.bunifuButton1.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton1.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton1.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton1.IconMarginLeft = 11;
            this.bunifuButton1.IconPadding = 10;
            this.bunifuButton1.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton1.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton1.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton1.IconSize = 25;
            this.bunifuButton1.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(41)))));
            this.bunifuButton1.IdleBorderRadius = 40;
            this.bunifuButton1.IdleBorderThickness = 1;
            this.bunifuButton1.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(41)))));
            this.bunifuButton1.IdleIconLeftImage = null;
            this.bunifuButton1.IdleIconRightImage = null;
            this.bunifuButton1.IndicateFocus = false;
            this.bunifuButton1.Location = new System.Drawing.Point(5, 277);
            this.bunifuButton1.Name = "bunifuButton1";
            this.bunifuButton1.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton1.OnDisabledState.BorderRadius = 40;
            this.bunifuButton1.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnDisabledState.BorderThickness = 1;
            this.bunifuButton1.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton1.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton1.OnDisabledState.IconLeftImage = null;
            this.bunifuButton1.OnDisabledState.IconRightImage = null;
            this.bunifuButton1.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton1.onHoverState.BorderRadius = 40;
            this.bunifuButton1.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.onHoverState.BorderThickness = 1;
            this.bunifuButton1.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton1.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.onHoverState.IconLeftImage = null;
            this.bunifuButton1.onHoverState.IconRightImage = null;
            this.bunifuButton1.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(41)))));
            this.bunifuButton1.OnIdleState.BorderRadius = 40;
            this.bunifuButton1.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnIdleState.BorderThickness = 1;
            this.bunifuButton1.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(41)))));
            this.bunifuButton1.OnIdleState.ForeColor = System.Drawing.Color.Snow;
            this.bunifuButton1.OnIdleState.IconLeftImage = null;
            this.bunifuButton1.OnIdleState.IconRightImage = null;
            this.bunifuButton1.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton1.OnPressedState.BorderRadius = 40;
            this.bunifuButton1.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnPressedState.BorderThickness = 1;
            this.bunifuButton1.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton1.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.OnPressedState.IconLeftImage = null;
            this.bunifuButton1.OnPressedState.IconRightImage = null;
            this.bunifuButton1.Size = new System.Drawing.Size(408, 49);
            this.bunifuButton1.TabIndex = 11;
            this.bunifuButton1.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton1.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton1.TextMarginLeft = 0;
            this.bunifuButton1.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButton1.UseDefaultRadiusAndThickness = true;
            // 
            // pictureBox1
            // 
            this.pictureBox1.AllowFocused = false;
            this.pictureBox1.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.pictureBox1.AutoSizeHeight = true;
            this.pictureBox1.BorderRadius = 79;
            this.pictureBox1.Image = ((System.Drawing.Image)(resources.GetObject("pictureBox1.Image")));
            this.pictureBox1.IsCircle = true;
            this.pictureBox1.Location = new System.Drawing.Point(122, 69);
            this.pictureBox1.Name = "pictureBox1";
            this.pictureBox1.Size = new System.Drawing.Size(159, 159);
            this.pictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pictureBox1.TabIndex = 0;
            this.pictureBox1.TabStop = false;
            this.pictureBox1.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Circle;
            // 
            // bunifuPanel1
            // 
            this.bunifuPanel1.BackgroundColor = System.Drawing.Color.Snow;
            this.bunifuPanel1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel1.BackgroundImage")));
            this.bunifuPanel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel1.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuPanel1.BorderRadius = 40;
            this.bunifuPanel1.BorderThickness = 1;
            this.bunifuPanel1.Controls.Add(this.btn_autorization);
            this.bunifuPanel1.Controls.Add(this.btn_reg);
            this.bunifuPanel1.Controls.Add(this.tb_tel);
            this.bunifuPanel1.Controls.Add(this.tb_dol);
            this.bunifuPanel1.Controls.Add(this.tb_patronomic);
            this.bunifuPanel1.Controls.Add(this.tb_fam);
            this.bunifuPanel1.Controls.Add(this.tb_nam);
            this.bunifuPanel1.Controls.Add(this.bunifuLabel1);
            this.bunifuPanel1.Location = new System.Drawing.Point(85, 47);
            this.bunifuPanel1.Name = "bunifuPanel1";
            this.bunifuPanel1.ShowBorders = true;
            this.bunifuPanel1.Size = new System.Drawing.Size(641, 679);
            this.bunifuPanel1.TabIndex = 0;
            // 
            // btn_autorization
            // 
            this.btn_autorization.AllowParentOverrides = false;
            this.btn_autorization.AutoEllipsis = false;
            this.btn_autorization.Cursor = System.Windows.Forms.Cursors.UpArrow;
            this.btn_autorization.CursorType = System.Windows.Forms.Cursors.UpArrow;
            this.btn_autorization.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Italic);
            this.btn_autorization.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(179)))), ((int)(((byte)(179)))), ((int)(((byte)(181)))));
            this.btn_autorization.Location = new System.Drawing.Point(166, 620);
            this.btn_autorization.Name = "btn_autorization";
            this.btn_autorization.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.btn_autorization.Size = new System.Drawing.Size(283, 21);
            this.btn_autorization.TabIndex = 11;
            this.btn_autorization.Text = "Does your account already exist? Sign in!";
            this.btn_autorization.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.btn_autorization.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.btn_autorization.UseWaitCursor = true;
            // 
            // btn_reg
            // 
            this.btn_reg.AllowAnimations = true;
            this.btn_reg.AllowMouseEffects = true;
            this.btn_reg.AllowToggling = false;
            this.btn_reg.AnimationSpeed = 200;
            this.btn_reg.AutoGenerateColors = false;
            this.btn_reg.AutoRoundBorders = false;
            this.btn_reg.AutoSizeLeftIcon = true;
            this.btn_reg.AutoSizeRightIcon = true;
            this.btn_reg.BackColor = System.Drawing.Color.Transparent;
            this.btn_reg.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(41)))));
            this.btn_reg.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_reg.BackgroundImage")));
            this.btn_reg.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_reg.ButtonText = "SIGN UP";
            this.btn_reg.ButtonTextMarginLeft = 0;
            this.btn_reg.ColorContrastOnClick = 45;
            this.btn_reg.ColorContrastOnHover = 45;
            this.btn_reg.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btn_reg.CustomizableEdges = borderEdges2;
            this.btn_reg.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_reg.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_reg.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_reg.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_reg.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btn_reg.Font = new System.Drawing.Font("Segoe UI Semibold", 16F, System.Drawing.FontStyle.Bold);
            this.btn_reg.ForeColor = System.Drawing.Color.Snow;
            this.btn_reg.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_reg.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn_reg.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btn_reg.IconMarginLeft = 11;
            this.btn_reg.IconPadding = 10;
            this.btn_reg.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn_reg.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn_reg.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn_reg.IconSize = 25;
            this.btn_reg.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(41)))));
            this.btn_reg.IdleBorderRadius = 40;
            this.btn_reg.IdleBorderThickness = 1;
            this.btn_reg.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(41)))));
            this.btn_reg.IdleIconLeftImage = null;
            this.btn_reg.IdleIconRightImage = null;
            this.btn_reg.IndicateFocus = false;
            this.btn_reg.Location = new System.Drawing.Point(6, 565);
            this.btn_reg.Name = "btn_reg";
            this.btn_reg.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_reg.OnDisabledState.BorderRadius = 40;
            this.btn_reg.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_reg.OnDisabledState.BorderThickness = 1;
            this.btn_reg.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_reg.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_reg.OnDisabledState.IconLeftImage = null;
            this.btn_reg.OnDisabledState.IconRightImage = null;
            this.btn_reg.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btn_reg.onHoverState.BorderRadius = 40;
            this.btn_reg.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_reg.onHoverState.BorderThickness = 1;
            this.btn_reg.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btn_reg.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btn_reg.onHoverState.IconLeftImage = null;
            this.btn_reg.onHoverState.IconRightImage = null;
            this.btn_reg.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(41)))));
            this.btn_reg.OnIdleState.BorderRadius = 40;
            this.btn_reg.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_reg.OnIdleState.BorderThickness = 1;
            this.btn_reg.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(41)))));
            this.btn_reg.OnIdleState.ForeColor = System.Drawing.Color.Snow;
            this.btn_reg.OnIdleState.IconLeftImage = null;
            this.btn_reg.OnIdleState.IconRightImage = null;
            this.btn_reg.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_reg.OnPressedState.BorderRadius = 40;
            this.btn_reg.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_reg.OnPressedState.BorderThickness = 1;
            this.btn_reg.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_reg.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btn_reg.OnPressedState.IconLeftImage = null;
            this.btn_reg.OnPressedState.IconRightImage = null;
            this.btn_reg.Size = new System.Drawing.Size(635, 49);
            this.btn_reg.TabIndex = 10;
            this.btn_reg.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_reg.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn_reg.TextMarginLeft = 0;
            this.btn_reg.TextPadding = new System.Windows.Forms.Padding(0);
            this.btn_reg.UseDefaultRadiusAndThickness = true;
            // 
            // tb_tel
            // 
            this.tb_tel.AcceptsReturn = false;
            this.tb_tel.AcceptsTab = false;
            this.tb_tel.AnimationSpeed = 200;
            this.tb_tel.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tb_tel.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tb_tel.BackColor = System.Drawing.Color.Transparent;
            this.tb_tel.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tb_tel.BackgroundImage")));
            this.tb_tel.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tb_tel.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tb_tel.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tb_tel.BorderColorIdle = System.Drawing.Color.Silver;
            this.tb_tel.BorderRadius = 40;
            this.tb_tel.BorderThickness = 1;
            this.tb_tel.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tb_tel.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_tel.DefaultFont = new System.Drawing.Font("Segoe UI", 15F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.tb_tel.DefaultText = "";
            this.tb_tel.FillColor = System.Drawing.Color.White;
            this.tb_tel.HideSelection = true;
            this.tb_tel.IconLeft = null;
            this.tb_tel.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_tel.IconPadding = 10;
            this.tb_tel.IconRight = null;
            this.tb_tel.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_tel.Lines = new string[0];
            this.tb_tel.Location = new System.Drawing.Point(50, 339);
            this.tb_tel.MaxLength = 32767;
            this.tb_tel.MinimumSize = new System.Drawing.Size(1, 1);
            this.tb_tel.Modified = false;
            this.tb_tel.Multiline = false;
            this.tb_tel.Name = "tb_tel";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_tel.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tb_tel.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_tel.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_tel.OnIdleState = stateProperties16;
            this.tb_tel.Padding = new System.Windows.Forms.Padding(3);
            this.tb_tel.PasswordChar = '\0';
            this.tb_tel.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tb_tel.PlaceholderText = "Введите номер телефона";
            this.tb_tel.ReadOnly = false;
            this.tb_tel.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tb_tel.SelectedText = "";
            this.tb_tel.SelectionLength = 0;
            this.tb_tel.SelectionStart = 0;
            this.tb_tel.ShortcutsEnabled = true;
            this.tb_tel.Size = new System.Drawing.Size(538, 47);
            this.tb_tel.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tb_tel.TabIndex = 9;
            this.tb_tel.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.tb_tel.TextMarginBottom = 0;
            this.tb_tel.TextMarginLeft = 3;
            this.tb_tel.TextMarginTop = 0;
            this.tb_tel.TextPlaceholder = "Введите номер телефона";
            this.tb_tel.UseSystemPasswordChar = false;
            this.tb_tel.WordWrap = true;
            // 
            // tb_dol
            // 
            this.tb_dol.AcceptsReturn = false;
            this.tb_dol.AcceptsTab = false;
            this.tb_dol.AnimationSpeed = 200;
            this.tb_dol.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tb_dol.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tb_dol.BackColor = System.Drawing.Color.Transparent;
            this.tb_dol.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tb_dol.BackgroundImage")));
            this.tb_dol.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tb_dol.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tb_dol.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tb_dol.BorderColorIdle = System.Drawing.Color.Silver;
            this.tb_dol.BorderRadius = 40;
            this.tb_dol.BorderThickness = 1;
            this.tb_dol.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tb_dol.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_dol.DefaultFont = new System.Drawing.Font("Segoe UI", 15F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.tb_dol.DefaultText = "";
            this.tb_dol.FillColor = System.Drawing.Color.White;
            this.tb_dol.HideSelection = true;
            this.tb_dol.IconLeft = null;
            this.tb_dol.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_dol.IconPadding = 10;
            this.tb_dol.IconRight = null;
            this.tb_dol.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_dol.Lines = new string[0];
            this.tb_dol.Location = new System.Drawing.Point(50, 270);
            this.tb_dol.MaxLength = 32767;
            this.tb_dol.MinimumSize = new System.Drawing.Size(1, 1);
            this.tb_dol.Modified = false;
            this.tb_dol.Multiline = false;
            this.tb_dol.Name = "tb_dol";
            stateProperties17.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_dol.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tb_dol.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_dol.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_dol.OnIdleState = stateProperties20;
            this.tb_dol.Padding = new System.Windows.Forms.Padding(3);
            this.tb_dol.PasswordChar = '\0';
            this.tb_dol.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tb_dol.PlaceholderText = "Введите email";
            this.tb_dol.ReadOnly = false;
            this.tb_dol.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tb_dol.SelectedText = "";
            this.tb_dol.SelectionLength = 0;
            this.tb_dol.SelectionStart = 0;
            this.tb_dol.ShortcutsEnabled = true;
            this.tb_dol.Size = new System.Drawing.Size(538, 47);
            this.tb_dol.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tb_dol.TabIndex = 5;
            this.tb_dol.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.tb_dol.TextMarginBottom = 0;
            this.tb_dol.TextMarginLeft = 3;
            this.tb_dol.TextMarginTop = 0;
            this.tb_dol.TextPlaceholder = "Введите email";
            this.tb_dol.UseSystemPasswordChar = false;
            this.tb_dol.WordWrap = true;
            // 
            // tb_patronomic
            // 
            this.tb_patronomic.AcceptsReturn = false;
            this.tb_patronomic.AcceptsTab = false;
            this.tb_patronomic.AnimationSpeed = 200;
            this.tb_patronomic.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tb_patronomic.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tb_patronomic.BackColor = System.Drawing.Color.Transparent;
            this.tb_patronomic.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tb_patronomic.BackgroundImage")));
            this.tb_patronomic.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tb_patronomic.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tb_patronomic.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tb_patronomic.BorderColorIdle = System.Drawing.Color.Silver;
            this.tb_patronomic.BorderRadius = 40;
            this.tb_patronomic.BorderThickness = 1;
            this.tb_patronomic.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tb_patronomic.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_patronomic.DefaultFont = new System.Drawing.Font("Segoe UI", 15F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.tb_patronomic.DefaultText = "";
            this.tb_patronomic.FillColor = System.Drawing.Color.White;
            this.tb_patronomic.HideSelection = true;
            this.tb_patronomic.IconLeft = null;
            this.tb_patronomic.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_patronomic.IconPadding = 10;
            this.tb_patronomic.IconRight = null;
            this.tb_patronomic.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_patronomic.Lines = new string[0];
            this.tb_patronomic.Location = new System.Drawing.Point(50, 207);
            this.tb_patronomic.MaxLength = 32767;
            this.tb_patronomic.MinimumSize = new System.Drawing.Size(1, 1);
            this.tb_patronomic.Modified = false;
            this.tb_patronomic.Multiline = false;
            this.tb_patronomic.Name = "tb_patronomic";
            stateProperties21.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_patronomic.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tb_patronomic.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_patronomic.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.Silver;
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.Empty;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_patronomic.OnIdleState = stateProperties24;
            this.tb_patronomic.Padding = new System.Windows.Forms.Padding(3);
            this.tb_patronomic.PasswordChar = '\0';
            this.tb_patronomic.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tb_patronomic.PlaceholderText = "Введите отчество";
            this.tb_patronomic.ReadOnly = false;
            this.tb_patronomic.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tb_patronomic.SelectedText = "";
            this.tb_patronomic.SelectionLength = 0;
            this.tb_patronomic.SelectionStart = 0;
            this.tb_patronomic.ShortcutsEnabled = true;
            this.tb_patronomic.Size = new System.Drawing.Size(538, 47);
            this.tb_patronomic.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tb_patronomic.TabIndex = 4;
            this.tb_patronomic.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.tb_patronomic.TextMarginBottom = 0;
            this.tb_patronomic.TextMarginLeft = 3;
            this.tb_patronomic.TextMarginTop = 0;
            this.tb_patronomic.TextPlaceholder = "Введите отчество";
            this.tb_patronomic.UseSystemPasswordChar = false;
            this.tb_patronomic.WordWrap = true;
            // 
            // tb_fam
            // 
            this.tb_fam.AcceptsReturn = false;
            this.tb_fam.AcceptsTab = false;
            this.tb_fam.AnimationSpeed = 200;
            this.tb_fam.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tb_fam.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tb_fam.BackColor = System.Drawing.Color.Transparent;
            this.tb_fam.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tb_fam.BackgroundImage")));
            this.tb_fam.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tb_fam.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tb_fam.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tb_fam.BorderColorIdle = System.Drawing.Color.Silver;
            this.tb_fam.BorderRadius = 40;
            this.tb_fam.BorderThickness = 1;
            this.tb_fam.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tb_fam.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_fam.DefaultFont = new System.Drawing.Font("Segoe UI", 15F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.tb_fam.DefaultText = "";
            this.tb_fam.FillColor = System.Drawing.Color.White;
            this.tb_fam.HideSelection = true;
            this.tb_fam.IconLeft = null;
            this.tb_fam.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_fam.IconPadding = 10;
            this.tb_fam.IconRight = null;
            this.tb_fam.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_fam.Lines = new string[0];
            this.tb_fam.Location = new System.Drawing.Point(50, 145);
            this.tb_fam.MaxLength = 32767;
            this.tb_fam.MinimumSize = new System.Drawing.Size(1, 1);
            this.tb_fam.Modified = false;
            this.tb_fam.Multiline = false;
            this.tb_fam.Name = "tb_fam";
            stateProperties25.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties25.FillColor = System.Drawing.Color.Empty;
            stateProperties25.ForeColor = System.Drawing.Color.Empty;
            stateProperties25.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_fam.OnActiveState = stateProperties25;
            stateProperties26.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties26.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties26.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties26.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tb_fam.OnDisabledState = stateProperties26;
            stateProperties27.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties27.FillColor = System.Drawing.Color.Empty;
            stateProperties27.ForeColor = System.Drawing.Color.Empty;
            stateProperties27.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_fam.OnHoverState = stateProperties27;
            stateProperties28.BorderColor = System.Drawing.Color.Silver;
            stateProperties28.FillColor = System.Drawing.Color.White;
            stateProperties28.ForeColor = System.Drawing.Color.Empty;
            stateProperties28.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_fam.OnIdleState = stateProperties28;
            this.tb_fam.Padding = new System.Windows.Forms.Padding(3);
            this.tb_fam.PasswordChar = '\0';
            this.tb_fam.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tb_fam.PlaceholderText = "Введите фамилию";
            this.tb_fam.ReadOnly = false;
            this.tb_fam.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tb_fam.SelectedText = "";
            this.tb_fam.SelectionLength = 0;
            this.tb_fam.SelectionStart = 0;
            this.tb_fam.ShortcutsEnabled = true;
            this.tb_fam.Size = new System.Drawing.Size(538, 47);
            this.tb_fam.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tb_fam.TabIndex = 3;
            this.tb_fam.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.tb_fam.TextMarginBottom = 0;
            this.tb_fam.TextMarginLeft = 3;
            this.tb_fam.TextMarginTop = 0;
            this.tb_fam.TextPlaceholder = "Введите фамилию";
            this.tb_fam.UseSystemPasswordChar = false;
            this.tb_fam.WordWrap = true;
            // 
            // tb_nam
            // 
            this.tb_nam.AcceptsReturn = false;
            this.tb_nam.AcceptsTab = false;
            this.tb_nam.AnimationSpeed = 200;
            this.tb_nam.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tb_nam.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tb_nam.BackColor = System.Drawing.Color.Transparent;
            this.tb_nam.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tb_nam.BackgroundImage")));
            this.tb_nam.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tb_nam.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tb_nam.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tb_nam.BorderColorIdle = System.Drawing.Color.Silver;
            this.tb_nam.BorderRadius = 40;
            this.tb_nam.BorderThickness = 1;
            this.tb_nam.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tb_nam.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_nam.DefaultFont = new System.Drawing.Font("Segoe UI", 15F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.tb_nam.DefaultText = "";
            this.tb_nam.FillColor = System.Drawing.Color.White;
            this.tb_nam.HideSelection = true;
            this.tb_nam.IconLeft = null;
            this.tb_nam.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_nam.IconPadding = 10;
            this.tb_nam.IconRight = null;
            this.tb_nam.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_nam.Lines = new string[0];
            this.tb_nam.Location = new System.Drawing.Point(50, 87);
            this.tb_nam.MaxLength = 32767;
            this.tb_nam.MinimumSize = new System.Drawing.Size(1, 1);
            this.tb_nam.Modified = false;
            this.tb_nam.Multiline = false;
            this.tb_nam.Name = "tb_nam";
            stateProperties29.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties29.FillColor = System.Drawing.Color.Empty;
            stateProperties29.ForeColor = System.Drawing.Color.Empty;
            stateProperties29.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_nam.OnActiveState = stateProperties29;
            stateProperties30.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties30.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties30.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties30.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tb_nam.OnDisabledState = stateProperties30;
            stateProperties31.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties31.FillColor = System.Drawing.Color.Empty;
            stateProperties31.ForeColor = System.Drawing.Color.Empty;
            stateProperties31.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_nam.OnHoverState = stateProperties31;
            stateProperties32.BorderColor = System.Drawing.Color.Silver;
            stateProperties32.FillColor = System.Drawing.Color.White;
            stateProperties32.ForeColor = System.Drawing.Color.Empty;
            stateProperties32.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_nam.OnIdleState = stateProperties32;
            this.tb_nam.Padding = new System.Windows.Forms.Padding(3);
            this.tb_nam.PasswordChar = '\0';
            this.tb_nam.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tb_nam.PlaceholderText = "Введите имя";
            this.tb_nam.ReadOnly = false;
            this.tb_nam.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tb_nam.SelectedText = "";
            this.tb_nam.SelectionLength = 0;
            this.tb_nam.SelectionStart = 0;
            this.tb_nam.ShortcutsEnabled = true;
            this.tb_nam.Size = new System.Drawing.Size(538, 47);
            this.tb_nam.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tb_nam.TabIndex = 2;
            this.tb_nam.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.tb_nam.TextMarginBottom = 0;
            this.tb_nam.TextMarginLeft = 3;
            this.tb_nam.TextMarginTop = 0;
            this.tb_nam.TextPlaceholder = "Введите имя";
            this.tb_nam.UseSystemPasswordChar = false;
            this.tb_nam.WordWrap = true;
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Font = new System.Drawing.Font("Arial Rounded MT Bold", 20.25F);
            this.bunifuLabel1.Location = new System.Drawing.Point(208, 3);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(224, 38);
            this.bunifuLabel1.TabIndex = 1;
            this.bunifuLabel1.Text = "Sign Up Here!";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // Registration
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(41)))));
            this.ClientSize = new System.Drawing.Size(1289, 762);
            this.Controls.Add(this.bunifuPictureBox3);
            this.Controls.Add(this.bunifuPanel2);
            this.Controls.Add(this.yt_Button1);
            this.Controls.Add(this.bunifuPanel1);
            this.Font = new System.Drawing.Font("Tahoma", 8.25F);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.Name = "Registration";
            this.Text = "СИБИРЬ";
            this.Load += new System.EventHandler(this.Registration_Load);
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox3)).EndInit();
            this.bunifuPanel2.ResumeLayout(false);
            this.bunifuPanel2.PerformLayout();
            this.yt_Button1.ResumeLayout(false);
            this.yt_Button1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).EndInit();
            this.bunifuPanel1.ResumeLayout(false);
            this.bunifuPanel1.PerformLayout();
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.Framework.UI.BunifuElipse bunifuElipse1;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel1;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.UI.WinForms.BunifuTextBox tb_tel;
        private Bunifu.UI.WinForms.BunifuTextBox tb_pass2;
        private Bunifu.UI.WinForms.BunifuTextBox tb_pass;
        private Bunifu.UI.WinForms.BunifuTextBox tb_logim;
        private Bunifu.UI.WinForms.BunifuTextBox tb_dol;
        private Bunifu.UI.WinForms.BunifuTextBox tb_patronomic;
        private Bunifu.UI.WinForms.BunifuTextBox tb_fam;
        private Bunifu.UI.WinForms.BunifuTextBox tb_nam;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_reg;
        private Bunifu.UI.WinForms.BunifuPanel yt_Button1;
        private Bunifu.UI.WinForms.BunifuPictureBox pictureBox1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton1;
        private Bunifu.UI.WinForms.BunifuLabel btn_autorization;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel2;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel3;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel2;
        private Bunifu.UI.WinForms.BunifuPictureBox bunifuPictureBox3;
    }
}