namespace Examen.Main
{
    partial class Staj
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Staj));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties29 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties30 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties31 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties32 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties33 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties34 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties35 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties36 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.bunifuElipse1 = new Bunifu.Framework.UI.BunifuElipse(this.components);
            this.bunifuPanel1 = new Bunifu.UI.WinForms.BunifuPanel();
            this.groupBox4 = new Bunifu.UI.WinForms.BunifuLabel();
            this.btn_save = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.dtp_stajRaboti = new Bunifu.UI.WinForms.BunifuDatePicker();
            this.bunifuLabel4 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel2 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel3 = new Bunifu.UI.WinForms.BunifuLabel();
            this.tb_PravoYear = new Bunifu.UI.WinForms.BunifuTextBox();
            this.tb_PravoMonth = new Bunifu.UI.WinForms.BunifuTextBox();
            this.tb_PravoDay = new Bunifu.UI.WinForms.BunifuTextBox();
            this.tb_NeprerivniyYear = new Bunifu.UI.WinForms.BunifuTextBox();
            this.tb_NeprerivniyMonth = new Bunifu.UI.WinForms.BunifuTextBox();
            this.tb_NeprerivniyDay = new Bunifu.UI.WinForms.BunifuTextBox();
            this.tb_ObshiyYear = new Bunifu.UI.WinForms.BunifuTextBox();
            this.tb_ObshiyMonth = new Bunifu.UI.WinForms.BunifuTextBox();
            this.tb_ObshiyDay = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuPictureBox3 = new Bunifu.UI.WinForms.BunifuPictureBox();
            this.bunifuPanel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox3)).BeginInit();
            this.SuspendLayout();
            // 
            // bunifuElipse1
            // 
            this.bunifuElipse1.ElipseRadius = 40;
            this.bunifuElipse1.TargetControl = this;
            // 
            // bunifuPanel1
            // 
            this.bunifuPanel1.BackgroundColor = System.Drawing.Color.Snow;
            this.bunifuPanel1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel1.BackgroundImage")));
            this.bunifuPanel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel1.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuPanel1.BorderRadius = 40;
            this.bunifuPanel1.BorderThickness = 1;
            this.bunifuPanel1.Controls.Add(this.bunifuPictureBox3);
            this.bunifuPanel1.Controls.Add(this.groupBox4);
            this.bunifuPanel1.Controls.Add(this.btn_save);
            this.bunifuPanel1.Controls.Add(this.dtp_stajRaboti);
            this.bunifuPanel1.Controls.Add(this.bunifuLabel4);
            this.bunifuPanel1.Controls.Add(this.bunifuLabel2);
            this.bunifuPanel1.Controls.Add(this.bunifuLabel1);
            this.bunifuPanel1.Controls.Add(this.bunifuLabel3);
            this.bunifuPanel1.Controls.Add(this.tb_PravoYear);
            this.bunifuPanel1.Controls.Add(this.tb_PravoMonth);
            this.bunifuPanel1.Controls.Add(this.tb_PravoDay);
            this.bunifuPanel1.Controls.Add(this.tb_NeprerivniyYear);
            this.bunifuPanel1.Controls.Add(this.tb_NeprerivniyMonth);
            this.bunifuPanel1.Controls.Add(this.tb_NeprerivniyDay);
            this.bunifuPanel1.Controls.Add(this.tb_ObshiyYear);
            this.bunifuPanel1.Controls.Add(this.tb_ObshiyMonth);
            this.bunifuPanel1.Controls.Add(this.tb_ObshiyDay);
            this.bunifuPanel1.Location = new System.Drawing.Point(27, 26);
            this.bunifuPanel1.Name = "bunifuPanel1";
            this.bunifuPanel1.ShowBorders = true;
            this.bunifuPanel1.Size = new System.Drawing.Size(669, 369);
            this.bunifuPanel1.TabIndex = 0;
            // 
            // groupBox4
            // 
            this.groupBox4.AllowParentOverrides = false;
            this.groupBox4.AutoEllipsis = false;
            this.groupBox4.CursorType = null;
            this.groupBox4.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Italic);
            this.groupBox4.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(41)))));
            this.groupBox4.Location = new System.Drawing.Point(19, 3);
            this.groupBox4.Name = "groupBox4";
            this.groupBox4.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.groupBox4.Size = new System.Drawing.Size(0, 0);
            this.groupBox4.TabIndex = 24;
            this.groupBox4.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.groupBox4.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // btn_save
            // 
            this.btn_save.AllowAnimations = true;
            this.btn_save.AllowMouseEffects = true;
            this.btn_save.AllowToggling = false;
            this.btn_save.AnimationSpeed = 200;
            this.btn_save.AutoGenerateColors = false;
            this.btn_save.AutoRoundBorders = false;
            this.btn_save.AutoSizeLeftIcon = true;
            this.btn_save.AutoSizeRightIcon = true;
            this.btn_save.BackColor = System.Drawing.Color.Transparent;
            this.btn_save.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(41)))));
            this.btn_save.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_save.BackgroundImage")));
            this.btn_save.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_save.ButtonText = "Добавить/Изменить";
            this.btn_save.ButtonTextMarginLeft = 0;
            this.btn_save.ColorContrastOnClick = 45;
            this.btn_save.ColorContrastOnHover = 45;
            this.btn_save.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btn_save.CustomizableEdges = borderEdges1;
            this.btn_save.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_save.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_save.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_save.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_save.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btn_save.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Italic);
            this.btn_save.ForeColor = System.Drawing.Color.White;
            this.btn_save.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_save.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn_save.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btn_save.IconMarginLeft = 11;
            this.btn_save.IconPadding = 10;
            this.btn_save.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn_save.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn_save.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn_save.IconSize = 25;
            this.btn_save.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(41)))));
            this.btn_save.IdleBorderRadius = 40;
            this.btn_save.IdleBorderThickness = 1;
            this.btn_save.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(41)))));
            this.btn_save.IdleIconLeftImage = null;
            this.btn_save.IdleIconRightImage = null;
            this.btn_save.IndicateFocus = false;
            this.btn_save.Location = new System.Drawing.Point(19, 301);
            this.btn_save.Name = "btn_save";
            this.btn_save.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_save.OnDisabledState.BorderRadius = 40;
            this.btn_save.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_save.OnDisabledState.BorderThickness = 1;
            this.btn_save.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_save.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_save.OnDisabledState.IconLeftImage = null;
            this.btn_save.OnDisabledState.IconRightImage = null;
            this.btn_save.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btn_save.onHoverState.BorderRadius = 40;
            this.btn_save.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_save.onHoverState.BorderThickness = 1;
            this.btn_save.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btn_save.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btn_save.onHoverState.IconLeftImage = null;
            this.btn_save.onHoverState.IconRightImage = null;
            this.btn_save.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(41)))));
            this.btn_save.OnIdleState.BorderRadius = 40;
            this.btn_save.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_save.OnIdleState.BorderThickness = 1;
            this.btn_save.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(41)))));
            this.btn_save.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btn_save.OnIdleState.IconLeftImage = null;
            this.btn_save.OnIdleState.IconRightImage = null;
            this.btn_save.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_save.OnPressedState.BorderRadius = 40;
            this.btn_save.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_save.OnPressedState.BorderThickness = 1;
            this.btn_save.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_save.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btn_save.OnPressedState.IconLeftImage = null;
            this.btn_save.OnPressedState.IconRightImage = null;
            this.btn_save.Size = new System.Drawing.Size(642, 37);
            this.btn_save.TabIndex = 23;
            this.btn_save.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_save.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn_save.TextMarginLeft = 0;
            this.btn_save.TextPadding = new System.Windows.Forms.Padding(0);
            this.btn_save.UseDefaultRadiusAndThickness = true;
            // 
            // dtp_stajRaboti
            // 
            this.dtp_stajRaboti.BackColor = System.Drawing.Color.Transparent;
            this.dtp_stajRaboti.BorderRadius = 17;
            this.dtp_stajRaboti.Color = System.Drawing.Color.Silver;
            this.dtp_stajRaboti.DateBorderThickness = Bunifu.UI.WinForms.BunifuDatePicker.BorderThickness.Thin;
            this.dtp_stajRaboti.DateTextAlign = Bunifu.UI.WinForms.BunifuDatePicker.TextAlign.Left;
            this.dtp_stajRaboti.DisabledColor = System.Drawing.Color.Gray;
            this.dtp_stajRaboti.DisplayWeekNumbers = false;
            this.dtp_stajRaboti.DPHeight = 0;
            this.dtp_stajRaboti.DropDownAlign = System.Windows.Forms.LeftRightAlignment.Right;
            this.dtp_stajRaboti.FillDatePicker = false;
            this.dtp_stajRaboti.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.dtp_stajRaboti.ForeColor = System.Drawing.Color.Black;
            this.dtp_stajRaboti.Icon = ((System.Drawing.Image)(resources.GetObject("dtp_stajRaboti.Icon")));
            this.dtp_stajRaboti.IconColor = System.Drawing.Color.Gray;
            this.dtp_stajRaboti.IconLocation = Bunifu.UI.WinForms.BunifuDatePicker.Indicator.Right;
            this.dtp_stajRaboti.LeftTextMargin = 5;
            this.dtp_stajRaboti.Location = new System.Drawing.Point(367, 38);
            this.dtp_stajRaboti.MinimumSize = new System.Drawing.Size(4, 32);
            this.dtp_stajRaboti.Name = "dtp_stajRaboti";
            this.dtp_stajRaboti.Size = new System.Drawing.Size(281, 32);
            this.dtp_stajRaboti.TabIndex = 22;
            this.dtp_stajRaboti.Value = new System.DateTime(2023, 10, 12, 4, 5, 0, 0);
            // 
            // bunifuLabel4
            // 
            this.bunifuLabel4.AllowParentOverrides = false;
            this.bunifuLabel4.AutoEllipsis = false;
            this.bunifuLabel4.CursorType = null;
            this.bunifuLabel4.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Italic);
            this.bunifuLabel4.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(41)))));
            this.bunifuLabel4.Location = new System.Drawing.Point(227, 42);
            this.bunifuLabel4.Name = "bunifuLabel4";
            this.bunifuLabel4.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel4.Size = new System.Drawing.Size(134, 21);
            this.bunifuLabel4.TabIndex = 21;
            this.bunifuLabel4.Text = "Стаж работы по:";
            this.bunifuLabel4.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel4.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel2
            // 
            this.bunifuLabel2.AllowParentOverrides = false;
            this.bunifuLabel2.AutoEllipsis = false;
            this.bunifuLabel2.CursorType = null;
            this.bunifuLabel2.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Italic);
            this.bunifuLabel2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(41)))));
            this.bunifuLabel2.Location = new System.Drawing.Point(19, 220);
            this.bunifuLabel2.Name = "bunifuLabel2";
            this.bunifuLabel2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel2.Size = new System.Drawing.Size(322, 21);
            this.bunifuLabel2.TabIndex = 20;
            this.bunifuLabel2.Text = "Дающий право на надбавку за выслугу лет ";
            this.bunifuLabel2.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel2.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.CursorType = null;
            this.bunifuLabel1.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Italic);
            this.bunifuLabel1.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(41)))));
            this.bunifuLabel1.Location = new System.Drawing.Point(19, 146);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(105, 21);
            this.bunifuLabel1.TabIndex = 19;
            this.bunifuLabel1.Text = "Непрерывный:";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel3
            // 
            this.bunifuLabel3.AllowParentOverrides = false;
            this.bunifuLabel3.AutoEllipsis = false;
            this.bunifuLabel3.CursorType = null;
            this.bunifuLabel3.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Italic);
            this.bunifuLabel3.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(41)))));
            this.bunifuLabel3.Location = new System.Drawing.Point(19, 30);
            this.bunifuLabel3.Name = "bunifuLabel3";
            this.bunifuLabel3.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel3.Size = new System.Drawing.Size(56, 21);
            this.bunifuLabel3.TabIndex = 18;
            this.bunifuLabel3.Text = "Общий:";
            this.bunifuLabel3.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel3.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // tb_PravoYear
            // 
            this.tb_PravoYear.AcceptsReturn = false;
            this.tb_PravoYear.AcceptsTab = false;
            this.tb_PravoYear.AnimationSpeed = 200;
            this.tb_PravoYear.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tb_PravoYear.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tb_PravoYear.BackColor = System.Drawing.Color.Transparent;
            this.tb_PravoYear.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tb_PravoYear.BackgroundImage")));
            this.tb_PravoYear.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tb_PravoYear.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tb_PravoYear.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tb_PravoYear.BorderColorIdle = System.Drawing.Color.Silver;
            this.tb_PravoYear.BorderRadius = 40;
            this.tb_PravoYear.BorderThickness = 1;
            this.tb_PravoYear.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tb_PravoYear.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_PravoYear.DefaultFont = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Italic);
            this.tb_PravoYear.DefaultText = "";
            this.tb_PravoYear.FillColor = System.Drawing.Color.White;
            this.tb_PravoYear.HideSelection = true;
            this.tb_PravoYear.IconLeft = null;
            this.tb_PravoYear.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_PravoYear.IconPadding = 10;
            this.tb_PravoYear.IconRight = null;
            this.tb_PravoYear.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_PravoYear.Lines = new string[0];
            this.tb_PravoYear.Location = new System.Drawing.Point(461, 247);
            this.tb_PravoYear.MaxLength = 32767;
            this.tb_PravoYear.MinimumSize = new System.Drawing.Size(1, 1);
            this.tb_PravoYear.Modified = false;
            this.tb_PravoYear.Multiline = false;
            this.tb_PravoYear.Name = "tb_PravoYear";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_PravoYear.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tb_PravoYear.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_PravoYear.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_PravoYear.OnIdleState = stateProperties4;
            this.tb_PravoYear.Padding = new System.Windows.Forms.Padding(3);
            this.tb_PravoYear.PasswordChar = '\0';
            this.tb_PravoYear.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tb_PravoYear.PlaceholderText = "Лет";
            this.tb_PravoYear.ReadOnly = false;
            this.tb_PravoYear.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tb_PravoYear.SelectedText = "";
            this.tb_PravoYear.SelectionLength = 0;
            this.tb_PravoYear.SelectionStart = 0;
            this.tb_PravoYear.ShortcutsEnabled = true;
            this.tb_PravoYear.Size = new System.Drawing.Size(187, 36);
            this.tb_PravoYear.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tb_PravoYear.TabIndex = 11;
            this.tb_PravoYear.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tb_PravoYear.TextMarginBottom = 0;
            this.tb_PravoYear.TextMarginLeft = 3;
            this.tb_PravoYear.TextMarginTop = 0;
            this.tb_PravoYear.TextPlaceholder = "Лет";
            this.tb_PravoYear.UseSystemPasswordChar = false;
            this.tb_PravoYear.WordWrap = true;
            // 
            // tb_PravoMonth
            // 
            this.tb_PravoMonth.AcceptsReturn = false;
            this.tb_PravoMonth.AcceptsTab = false;
            this.tb_PravoMonth.AnimationSpeed = 200;
            this.tb_PravoMonth.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tb_PravoMonth.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tb_PravoMonth.BackColor = System.Drawing.Color.Transparent;
            this.tb_PravoMonth.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tb_PravoMonth.BackgroundImage")));
            this.tb_PravoMonth.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tb_PravoMonth.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tb_PravoMonth.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tb_PravoMonth.BorderColorIdle = System.Drawing.Color.Silver;
            this.tb_PravoMonth.BorderRadius = 40;
            this.tb_PravoMonth.BorderThickness = 1;
            this.tb_PravoMonth.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tb_PravoMonth.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_PravoMonth.DefaultFont = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Italic);
            this.tb_PravoMonth.DefaultText = "";
            this.tb_PravoMonth.FillColor = System.Drawing.Color.White;
            this.tb_PravoMonth.HideSelection = true;
            this.tb_PravoMonth.IconLeft = null;
            this.tb_PravoMonth.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_PravoMonth.IconPadding = 10;
            this.tb_PravoMonth.IconRight = null;
            this.tb_PravoMonth.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_PravoMonth.Lines = new string[0];
            this.tb_PravoMonth.Location = new System.Drawing.Point(239, 247);
            this.tb_PravoMonth.MaxLength = 32767;
            this.tb_PravoMonth.MinimumSize = new System.Drawing.Size(1, 1);
            this.tb_PravoMonth.Modified = false;
            this.tb_PravoMonth.Multiline = false;
            this.tb_PravoMonth.Name = "tb_PravoMonth";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_PravoMonth.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tb_PravoMonth.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_PravoMonth.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_PravoMonth.OnIdleState = stateProperties8;
            this.tb_PravoMonth.Padding = new System.Windows.Forms.Padding(3);
            this.tb_PravoMonth.PasswordChar = '\0';
            this.tb_PravoMonth.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tb_PravoMonth.PlaceholderText = "Месяцев";
            this.tb_PravoMonth.ReadOnly = false;
            this.tb_PravoMonth.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tb_PravoMonth.SelectedText = "";
            this.tb_PravoMonth.SelectionLength = 0;
            this.tb_PravoMonth.SelectionStart = 0;
            this.tb_PravoMonth.ShortcutsEnabled = true;
            this.tb_PravoMonth.Size = new System.Drawing.Size(187, 36);
            this.tb_PravoMonth.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tb_PravoMonth.TabIndex = 10;
            this.tb_PravoMonth.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tb_PravoMonth.TextMarginBottom = 0;
            this.tb_PravoMonth.TextMarginLeft = 3;
            this.tb_PravoMonth.TextMarginTop = 0;
            this.tb_PravoMonth.TextPlaceholder = "Месяцев";
            this.tb_PravoMonth.UseSystemPasswordChar = false;
            this.tb_PravoMonth.WordWrap = true;
            // 
            // tb_PravoDay
            // 
            this.tb_PravoDay.AcceptsReturn = false;
            this.tb_PravoDay.AcceptsTab = false;
            this.tb_PravoDay.AnimationSpeed = 200;
            this.tb_PravoDay.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tb_PravoDay.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tb_PravoDay.BackColor = System.Drawing.Color.Transparent;
            this.tb_PravoDay.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tb_PravoDay.BackgroundImage")));
            this.tb_PravoDay.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tb_PravoDay.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tb_PravoDay.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tb_PravoDay.BorderColorIdle = System.Drawing.Color.Silver;
            this.tb_PravoDay.BorderRadius = 40;
            this.tb_PravoDay.BorderThickness = 1;
            this.tb_PravoDay.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tb_PravoDay.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_PravoDay.DefaultFont = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Italic);
            this.tb_PravoDay.DefaultText = "";
            this.tb_PravoDay.FillColor = System.Drawing.Color.White;
            this.tb_PravoDay.HideSelection = true;
            this.tb_PravoDay.IconLeft = null;
            this.tb_PravoDay.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_PravoDay.IconPadding = 10;
            this.tb_PravoDay.IconRight = null;
            this.tb_PravoDay.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_PravoDay.Lines = new string[0];
            this.tb_PravoDay.Location = new System.Drawing.Point(19, 247);
            this.tb_PravoDay.MaxLength = 32767;
            this.tb_PravoDay.MinimumSize = new System.Drawing.Size(1, 1);
            this.tb_PravoDay.Modified = false;
            this.tb_PravoDay.Multiline = false;
            this.tb_PravoDay.Name = "tb_PravoDay";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_PravoDay.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tb_PravoDay.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_PravoDay.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_PravoDay.OnIdleState = stateProperties12;
            this.tb_PravoDay.Padding = new System.Windows.Forms.Padding(3);
            this.tb_PravoDay.PasswordChar = '\0';
            this.tb_PravoDay.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tb_PravoDay.PlaceholderText = "Дней";
            this.tb_PravoDay.ReadOnly = false;
            this.tb_PravoDay.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tb_PravoDay.SelectedText = "";
            this.tb_PravoDay.SelectionLength = 0;
            this.tb_PravoDay.SelectionStart = 0;
            this.tb_PravoDay.ShortcutsEnabled = true;
            this.tb_PravoDay.Size = new System.Drawing.Size(187, 36);
            this.tb_PravoDay.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tb_PravoDay.TabIndex = 9;
            this.tb_PravoDay.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tb_PravoDay.TextMarginBottom = 0;
            this.tb_PravoDay.TextMarginLeft = 3;
            this.tb_PravoDay.TextMarginTop = 0;
            this.tb_PravoDay.TextPlaceholder = "Дней";
            this.tb_PravoDay.UseSystemPasswordChar = false;
            this.tb_PravoDay.WordWrap = true;
            // 
            // tb_NeprerivniyYear
            // 
            this.tb_NeprerivniyYear.AcceptsReturn = false;
            this.tb_NeprerivniyYear.AcceptsTab = false;
            this.tb_NeprerivniyYear.AnimationSpeed = 200;
            this.tb_NeprerivniyYear.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tb_NeprerivniyYear.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tb_NeprerivniyYear.BackColor = System.Drawing.Color.Transparent;
            this.tb_NeprerivniyYear.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tb_NeprerivniyYear.BackgroundImage")));
            this.tb_NeprerivniyYear.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tb_NeprerivniyYear.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tb_NeprerivniyYear.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tb_NeprerivniyYear.BorderColorIdle = System.Drawing.Color.Silver;
            this.tb_NeprerivniyYear.BorderRadius = 40;
            this.tb_NeprerivniyYear.BorderThickness = 1;
            this.tb_NeprerivniyYear.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tb_NeprerivniyYear.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_NeprerivniyYear.DefaultFont = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Italic);
            this.tb_NeprerivniyYear.DefaultText = "";
            this.tb_NeprerivniyYear.FillColor = System.Drawing.Color.White;
            this.tb_NeprerivniyYear.HideSelection = true;
            this.tb_NeprerivniyYear.IconLeft = null;
            this.tb_NeprerivniyYear.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_NeprerivniyYear.IconPadding = 10;
            this.tb_NeprerivniyYear.IconRight = null;
            this.tb_NeprerivniyYear.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_NeprerivniyYear.Lines = new string[0];
            this.tb_NeprerivniyYear.Location = new System.Drawing.Point(461, 170);
            this.tb_NeprerivniyYear.MaxLength = 32767;
            this.tb_NeprerivniyYear.MinimumSize = new System.Drawing.Size(1, 1);
            this.tb_NeprerivniyYear.Modified = false;
            this.tb_NeprerivniyYear.Multiline = false;
            this.tb_NeprerivniyYear.Name = "tb_NeprerivniyYear";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_NeprerivniyYear.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tb_NeprerivniyYear.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_NeprerivniyYear.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_NeprerivniyYear.OnIdleState = stateProperties16;
            this.tb_NeprerivniyYear.Padding = new System.Windows.Forms.Padding(3);
            this.tb_NeprerivniyYear.PasswordChar = '\0';
            this.tb_NeprerivniyYear.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tb_NeprerivniyYear.PlaceholderText = "Лет";
            this.tb_NeprerivniyYear.ReadOnly = false;
            this.tb_NeprerivniyYear.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tb_NeprerivniyYear.SelectedText = "";
            this.tb_NeprerivniyYear.SelectionLength = 0;
            this.tb_NeprerivniyYear.SelectionStart = 0;
            this.tb_NeprerivniyYear.ShortcutsEnabled = true;
            this.tb_NeprerivniyYear.Size = new System.Drawing.Size(187, 36);
            this.tb_NeprerivniyYear.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tb_NeprerivniyYear.TabIndex = 8;
            this.tb_NeprerivniyYear.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tb_NeprerivniyYear.TextMarginBottom = 0;
            this.tb_NeprerivniyYear.TextMarginLeft = 3;
            this.tb_NeprerivniyYear.TextMarginTop = 0;
            this.tb_NeprerivniyYear.TextPlaceholder = "Лет";
            this.tb_NeprerivniyYear.UseSystemPasswordChar = false;
            this.tb_NeprerivniyYear.WordWrap = true;
            // 
            // tb_NeprerivniyMonth
            // 
            this.tb_NeprerivniyMonth.AcceptsReturn = false;
            this.tb_NeprerivniyMonth.AcceptsTab = false;
            this.tb_NeprerivniyMonth.AnimationSpeed = 200;
            this.tb_NeprerivniyMonth.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tb_NeprerivniyMonth.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tb_NeprerivniyMonth.BackColor = System.Drawing.Color.Transparent;
            this.tb_NeprerivniyMonth.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tb_NeprerivniyMonth.BackgroundImage")));
            this.tb_NeprerivniyMonth.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tb_NeprerivniyMonth.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tb_NeprerivniyMonth.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tb_NeprerivniyMonth.BorderColorIdle = System.Drawing.Color.Silver;
            this.tb_NeprerivniyMonth.BorderRadius = 40;
            this.tb_NeprerivniyMonth.BorderThickness = 1;
            this.tb_NeprerivniyMonth.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tb_NeprerivniyMonth.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_NeprerivniyMonth.DefaultFont = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Italic);
            this.tb_NeprerivniyMonth.DefaultText = "";
            this.tb_NeprerivniyMonth.FillColor = System.Drawing.Color.White;
            this.tb_NeprerivniyMonth.HideSelection = true;
            this.tb_NeprerivniyMonth.IconLeft = null;
            this.tb_NeprerivniyMonth.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_NeprerivniyMonth.IconPadding = 10;
            this.tb_NeprerivniyMonth.IconRight = null;
            this.tb_NeprerivniyMonth.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_NeprerivniyMonth.Lines = new string[0];
            this.tb_NeprerivniyMonth.Location = new System.Drawing.Point(239, 170);
            this.tb_NeprerivniyMonth.MaxLength = 32767;
            this.tb_NeprerivniyMonth.MinimumSize = new System.Drawing.Size(1, 1);
            this.tb_NeprerivniyMonth.Modified = false;
            this.tb_NeprerivniyMonth.Multiline = false;
            this.tb_NeprerivniyMonth.Name = "tb_NeprerivniyMonth";
            stateProperties17.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_NeprerivniyMonth.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tb_NeprerivniyMonth.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_NeprerivniyMonth.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_NeprerivniyMonth.OnIdleState = stateProperties20;
            this.tb_NeprerivniyMonth.Padding = new System.Windows.Forms.Padding(3);
            this.tb_NeprerivniyMonth.PasswordChar = '\0';
            this.tb_NeprerivniyMonth.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tb_NeprerivniyMonth.PlaceholderText = "Месяцев";
            this.tb_NeprerivniyMonth.ReadOnly = false;
            this.tb_NeprerivniyMonth.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tb_NeprerivniyMonth.SelectedText = "";
            this.tb_NeprerivniyMonth.SelectionLength = 0;
            this.tb_NeprerivniyMonth.SelectionStart = 0;
            this.tb_NeprerivniyMonth.ShortcutsEnabled = true;
            this.tb_NeprerivniyMonth.Size = new System.Drawing.Size(187, 36);
            this.tb_NeprerivniyMonth.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tb_NeprerivniyMonth.TabIndex = 7;
            this.tb_NeprerivniyMonth.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tb_NeprerivniyMonth.TextMarginBottom = 0;
            this.tb_NeprerivniyMonth.TextMarginLeft = 3;
            this.tb_NeprerivniyMonth.TextMarginTop = 0;
            this.tb_NeprerivniyMonth.TextPlaceholder = "Месяцев";
            this.tb_NeprerivniyMonth.UseSystemPasswordChar = false;
            this.tb_NeprerivniyMonth.WordWrap = true;
            // 
            // tb_NeprerivniyDay
            // 
            this.tb_NeprerivniyDay.AcceptsReturn = false;
            this.tb_NeprerivniyDay.AcceptsTab = false;
            this.tb_NeprerivniyDay.AnimationSpeed = 200;
            this.tb_NeprerivniyDay.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tb_NeprerivniyDay.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tb_NeprerivniyDay.BackColor = System.Drawing.Color.Transparent;
            this.tb_NeprerivniyDay.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tb_NeprerivniyDay.BackgroundImage")));
            this.tb_NeprerivniyDay.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tb_NeprerivniyDay.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tb_NeprerivniyDay.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tb_NeprerivniyDay.BorderColorIdle = System.Drawing.Color.Silver;
            this.tb_NeprerivniyDay.BorderRadius = 40;
            this.tb_NeprerivniyDay.BorderThickness = 1;
            this.tb_NeprerivniyDay.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tb_NeprerivniyDay.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_NeprerivniyDay.DefaultFont = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Italic);
            this.tb_NeprerivniyDay.DefaultText = "";
            this.tb_NeprerivniyDay.FillColor = System.Drawing.Color.White;
            this.tb_NeprerivniyDay.HideSelection = true;
            this.tb_NeprerivniyDay.IconLeft = null;
            this.tb_NeprerivniyDay.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_NeprerivniyDay.IconPadding = 10;
            this.tb_NeprerivniyDay.IconRight = null;
            this.tb_NeprerivniyDay.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_NeprerivniyDay.Lines = new string[0];
            this.tb_NeprerivniyDay.Location = new System.Drawing.Point(19, 170);
            this.tb_NeprerivniyDay.MaxLength = 32767;
            this.tb_NeprerivniyDay.MinimumSize = new System.Drawing.Size(1, 1);
            this.tb_NeprerivniyDay.Modified = false;
            this.tb_NeprerivniyDay.Multiline = false;
            this.tb_NeprerivniyDay.Name = "tb_NeprerivniyDay";
            stateProperties21.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_NeprerivniyDay.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tb_NeprerivniyDay.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_NeprerivniyDay.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.Silver;
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.Empty;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_NeprerivniyDay.OnIdleState = stateProperties24;
            this.tb_NeprerivniyDay.Padding = new System.Windows.Forms.Padding(3);
            this.tb_NeprerivniyDay.PasswordChar = '\0';
            this.tb_NeprerivniyDay.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tb_NeprerivniyDay.PlaceholderText = "Дней";
            this.tb_NeprerivniyDay.ReadOnly = false;
            this.tb_NeprerivniyDay.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tb_NeprerivniyDay.SelectedText = "";
            this.tb_NeprerivniyDay.SelectionLength = 0;
            this.tb_NeprerivniyDay.SelectionStart = 0;
            this.tb_NeprerivniyDay.ShortcutsEnabled = true;
            this.tb_NeprerivniyDay.Size = new System.Drawing.Size(187, 36);
            this.tb_NeprerivniyDay.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tb_NeprerivniyDay.TabIndex = 6;
            this.tb_NeprerivniyDay.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tb_NeprerivniyDay.TextMarginBottom = 0;
            this.tb_NeprerivniyDay.TextMarginLeft = 3;
            this.tb_NeprerivniyDay.TextMarginTop = 0;
            this.tb_NeprerivniyDay.TextPlaceholder = "Дней";
            this.tb_NeprerivniyDay.UseSystemPasswordChar = false;
            this.tb_NeprerivniyDay.WordWrap = true;
            // 
            // tb_ObshiyYear
            // 
            this.tb_ObshiyYear.AcceptsReturn = false;
            this.tb_ObshiyYear.AcceptsTab = false;
            this.tb_ObshiyYear.AnimationSpeed = 200;
            this.tb_ObshiyYear.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tb_ObshiyYear.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tb_ObshiyYear.BackColor = System.Drawing.Color.Transparent;
            this.tb_ObshiyYear.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tb_ObshiyYear.BackgroundImage")));
            this.tb_ObshiyYear.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tb_ObshiyYear.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tb_ObshiyYear.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tb_ObshiyYear.BorderColorIdle = System.Drawing.Color.Silver;
            this.tb_ObshiyYear.BorderRadius = 40;
            this.tb_ObshiyYear.BorderThickness = 1;
            this.tb_ObshiyYear.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tb_ObshiyYear.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_ObshiyYear.DefaultFont = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Italic);
            this.tb_ObshiyYear.DefaultText = "";
            this.tb_ObshiyYear.FillColor = System.Drawing.Color.White;
            this.tb_ObshiyYear.HideSelection = true;
            this.tb_ObshiyYear.IconLeft = null;
            this.tb_ObshiyYear.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_ObshiyYear.IconPadding = 10;
            this.tb_ObshiyYear.IconRight = null;
            this.tb_ObshiyYear.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_ObshiyYear.Lines = new string[0];
            this.tb_ObshiyYear.Location = new System.Drawing.Point(461, 86);
            this.tb_ObshiyYear.MaxLength = 32767;
            this.tb_ObshiyYear.MinimumSize = new System.Drawing.Size(1, 1);
            this.tb_ObshiyYear.Modified = false;
            this.tb_ObshiyYear.Multiline = false;
            this.tb_ObshiyYear.Name = "tb_ObshiyYear";
            stateProperties25.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties25.FillColor = System.Drawing.Color.Empty;
            stateProperties25.ForeColor = System.Drawing.Color.Empty;
            stateProperties25.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_ObshiyYear.OnActiveState = stateProperties25;
            stateProperties26.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties26.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties26.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties26.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tb_ObshiyYear.OnDisabledState = stateProperties26;
            stateProperties27.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties27.FillColor = System.Drawing.Color.Empty;
            stateProperties27.ForeColor = System.Drawing.Color.Empty;
            stateProperties27.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_ObshiyYear.OnHoverState = stateProperties27;
            stateProperties28.BorderColor = System.Drawing.Color.Silver;
            stateProperties28.FillColor = System.Drawing.Color.White;
            stateProperties28.ForeColor = System.Drawing.Color.Empty;
            stateProperties28.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_ObshiyYear.OnIdleState = stateProperties28;
            this.tb_ObshiyYear.Padding = new System.Windows.Forms.Padding(3);
            this.tb_ObshiyYear.PasswordChar = '\0';
            this.tb_ObshiyYear.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tb_ObshiyYear.PlaceholderText = "Лет";
            this.tb_ObshiyYear.ReadOnly = false;
            this.tb_ObshiyYear.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tb_ObshiyYear.SelectedText = "";
            this.tb_ObshiyYear.SelectionLength = 0;
            this.tb_ObshiyYear.SelectionStart = 0;
            this.tb_ObshiyYear.ShortcutsEnabled = true;
            this.tb_ObshiyYear.Size = new System.Drawing.Size(187, 36);
            this.tb_ObshiyYear.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tb_ObshiyYear.TabIndex = 5;
            this.tb_ObshiyYear.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tb_ObshiyYear.TextMarginBottom = 0;
            this.tb_ObshiyYear.TextMarginLeft = 3;
            this.tb_ObshiyYear.TextMarginTop = 0;
            this.tb_ObshiyYear.TextPlaceholder = "Лет";
            this.tb_ObshiyYear.UseSystemPasswordChar = false;
            this.tb_ObshiyYear.WordWrap = true;
            // 
            // tb_ObshiyMonth
            // 
            this.tb_ObshiyMonth.AcceptsReturn = false;
            this.tb_ObshiyMonth.AcceptsTab = false;
            this.tb_ObshiyMonth.AnimationSpeed = 200;
            this.tb_ObshiyMonth.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tb_ObshiyMonth.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tb_ObshiyMonth.BackColor = System.Drawing.Color.Transparent;
            this.tb_ObshiyMonth.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tb_ObshiyMonth.BackgroundImage")));
            this.tb_ObshiyMonth.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tb_ObshiyMonth.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tb_ObshiyMonth.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tb_ObshiyMonth.BorderColorIdle = System.Drawing.Color.Silver;
            this.tb_ObshiyMonth.BorderRadius = 40;
            this.tb_ObshiyMonth.BorderThickness = 1;
            this.tb_ObshiyMonth.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tb_ObshiyMonth.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_ObshiyMonth.DefaultFont = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Italic);
            this.tb_ObshiyMonth.DefaultText = "";
            this.tb_ObshiyMonth.FillColor = System.Drawing.Color.White;
            this.tb_ObshiyMonth.HideSelection = true;
            this.tb_ObshiyMonth.IconLeft = null;
            this.tb_ObshiyMonth.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_ObshiyMonth.IconPadding = 10;
            this.tb_ObshiyMonth.IconRight = null;
            this.tb_ObshiyMonth.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_ObshiyMonth.Lines = new string[0];
            this.tb_ObshiyMonth.Location = new System.Drawing.Point(239, 86);
            this.tb_ObshiyMonth.MaxLength = 32767;
            this.tb_ObshiyMonth.MinimumSize = new System.Drawing.Size(1, 1);
            this.tb_ObshiyMonth.Modified = false;
            this.tb_ObshiyMonth.Multiline = false;
            this.tb_ObshiyMonth.Name = "tb_ObshiyMonth";
            stateProperties29.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties29.FillColor = System.Drawing.Color.Empty;
            stateProperties29.ForeColor = System.Drawing.Color.Empty;
            stateProperties29.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_ObshiyMonth.OnActiveState = stateProperties29;
            stateProperties30.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties30.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties30.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties30.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tb_ObshiyMonth.OnDisabledState = stateProperties30;
            stateProperties31.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties31.FillColor = System.Drawing.Color.Empty;
            stateProperties31.ForeColor = System.Drawing.Color.Empty;
            stateProperties31.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_ObshiyMonth.OnHoverState = stateProperties31;
            stateProperties32.BorderColor = System.Drawing.Color.Silver;
            stateProperties32.FillColor = System.Drawing.Color.White;
            stateProperties32.ForeColor = System.Drawing.Color.Empty;
            stateProperties32.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_ObshiyMonth.OnIdleState = stateProperties32;
            this.tb_ObshiyMonth.Padding = new System.Windows.Forms.Padding(3);
            this.tb_ObshiyMonth.PasswordChar = '\0';
            this.tb_ObshiyMonth.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tb_ObshiyMonth.PlaceholderText = "Месяцев";
            this.tb_ObshiyMonth.ReadOnly = false;
            this.tb_ObshiyMonth.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tb_ObshiyMonth.SelectedText = "";
            this.tb_ObshiyMonth.SelectionLength = 0;
            this.tb_ObshiyMonth.SelectionStart = 0;
            this.tb_ObshiyMonth.ShortcutsEnabled = true;
            this.tb_ObshiyMonth.Size = new System.Drawing.Size(187, 36);
            this.tb_ObshiyMonth.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tb_ObshiyMonth.TabIndex = 4;
            this.tb_ObshiyMonth.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tb_ObshiyMonth.TextMarginBottom = 0;
            this.tb_ObshiyMonth.TextMarginLeft = 3;
            this.tb_ObshiyMonth.TextMarginTop = 0;
            this.tb_ObshiyMonth.TextPlaceholder = "Месяцев";
            this.tb_ObshiyMonth.UseSystemPasswordChar = false;
            this.tb_ObshiyMonth.WordWrap = true;
            // 
            // tb_ObshiyDay
            // 
            this.tb_ObshiyDay.AcceptsReturn = false;
            this.tb_ObshiyDay.AcceptsTab = false;
            this.tb_ObshiyDay.AnimationSpeed = 200;
            this.tb_ObshiyDay.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tb_ObshiyDay.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tb_ObshiyDay.BackColor = System.Drawing.Color.Transparent;
            this.tb_ObshiyDay.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tb_ObshiyDay.BackgroundImage")));
            this.tb_ObshiyDay.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tb_ObshiyDay.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tb_ObshiyDay.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tb_ObshiyDay.BorderColorIdle = System.Drawing.Color.Silver;
            this.tb_ObshiyDay.BorderRadius = 40;
            this.tb_ObshiyDay.BorderThickness = 1;
            this.tb_ObshiyDay.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tb_ObshiyDay.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_ObshiyDay.DefaultFont = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Italic);
            this.tb_ObshiyDay.DefaultText = "";
            this.tb_ObshiyDay.FillColor = System.Drawing.Color.White;
            this.tb_ObshiyDay.HideSelection = true;
            this.tb_ObshiyDay.IconLeft = null;
            this.tb_ObshiyDay.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_ObshiyDay.IconPadding = 10;
            this.tb_ObshiyDay.IconRight = null;
            this.tb_ObshiyDay.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_ObshiyDay.Lines = new string[0];
            this.tb_ObshiyDay.Location = new System.Drawing.Point(19, 86);
            this.tb_ObshiyDay.MaxLength = 32767;
            this.tb_ObshiyDay.MinimumSize = new System.Drawing.Size(1, 1);
            this.tb_ObshiyDay.Modified = false;
            this.tb_ObshiyDay.Multiline = false;
            this.tb_ObshiyDay.Name = "tb_ObshiyDay";
            stateProperties33.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties33.FillColor = System.Drawing.Color.Empty;
            stateProperties33.ForeColor = System.Drawing.Color.Empty;
            stateProperties33.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_ObshiyDay.OnActiveState = stateProperties33;
            stateProperties34.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties34.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties34.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties34.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tb_ObshiyDay.OnDisabledState = stateProperties34;
            stateProperties35.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties35.FillColor = System.Drawing.Color.Empty;
            stateProperties35.ForeColor = System.Drawing.Color.Empty;
            stateProperties35.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_ObshiyDay.OnHoverState = stateProperties35;
            stateProperties36.BorderColor = System.Drawing.Color.Silver;
            stateProperties36.FillColor = System.Drawing.Color.White;
            stateProperties36.ForeColor = System.Drawing.Color.Empty;
            stateProperties36.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_ObshiyDay.OnIdleState = stateProperties36;
            this.tb_ObshiyDay.Padding = new System.Windows.Forms.Padding(3);
            this.tb_ObshiyDay.PasswordChar = '\0';
            this.tb_ObshiyDay.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tb_ObshiyDay.PlaceholderText = "Дней";
            this.tb_ObshiyDay.ReadOnly = false;
            this.tb_ObshiyDay.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tb_ObshiyDay.SelectedText = "";
            this.tb_ObshiyDay.SelectionLength = 0;
            this.tb_ObshiyDay.SelectionStart = 0;
            this.tb_ObshiyDay.ShortcutsEnabled = true;
            this.tb_ObshiyDay.Size = new System.Drawing.Size(187, 36);
            this.tb_ObshiyDay.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tb_ObshiyDay.TabIndex = 3;
            this.tb_ObshiyDay.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tb_ObshiyDay.TextMarginBottom = 0;
            this.tb_ObshiyDay.TextMarginLeft = 3;
            this.tb_ObshiyDay.TextMarginTop = 0;
            this.tb_ObshiyDay.TextPlaceholder = "Дней";
            this.tb_ObshiyDay.UseSystemPasswordChar = false;
            this.tb_ObshiyDay.WordWrap = true;
            // 
            // bunifuPictureBox3
            // 
            this.bunifuPictureBox3.AllowFocused = false;
            this.bunifuPictureBox3.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.bunifuPictureBox3.AutoSizeHeight = true;
            this.bunifuPictureBox3.BorderRadius = 12;
            this.bunifuPictureBox3.Image = global::Examen.Properties.Resources._1486564399_close_815122;
            this.bunifuPictureBox3.IsCircle = true;
            this.bunifuPictureBox3.Location = new System.Drawing.Point(624, 8);
            this.bunifuPictureBox3.Name = "bunifuPictureBox3";
            this.bunifuPictureBox3.Size = new System.Drawing.Size(24, 24);
            this.bunifuPictureBox3.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.bunifuPictureBox3.TabIndex = 25;
            this.bunifuPictureBox3.TabStop = false;
            this.bunifuPictureBox3.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Circle;
            this.bunifuPictureBox3.Click += new System.EventHandler(this.bunifuPictureBox3_Click);
            // 
            // Staj
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(41)))));
            this.ClientSize = new System.Drawing.Size(734, 424);
            this.Controls.Add(this.bunifuPanel1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Margin = new System.Windows.Forms.Padding(2);
            this.Name = "Staj";
            this.Text = "Рабочий стаж сотрудника";
            this.Load += new System.EventHandler(this.Form1_Load);
            this.bunifuPanel1.ResumeLayout(false);
            this.bunifuPanel1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox3)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.Framework.UI.BunifuElipse bunifuElipse1;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel1;
        private Bunifu.UI.WinForms.BunifuTextBox tb_PravoYear;
        private Bunifu.UI.WinForms.BunifuTextBox tb_PravoMonth;
        private Bunifu.UI.WinForms.BunifuTextBox tb_PravoDay;
        private Bunifu.UI.WinForms.BunifuTextBox tb_NeprerivniyYear;
        private Bunifu.UI.WinForms.BunifuTextBox tb_NeprerivniyMonth;
        private Bunifu.UI.WinForms.BunifuTextBox tb_NeprerivniyDay;
        private Bunifu.UI.WinForms.BunifuTextBox tb_ObshiyYear;
        private Bunifu.UI.WinForms.BunifuTextBox tb_ObshiyMonth;
        private Bunifu.UI.WinForms.BunifuTextBox tb_ObshiyDay;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel2;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel3;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel4;
        private Bunifu.UI.WinForms.BunifuDatePicker dtp_stajRaboti;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_save;
        private Bunifu.UI.WinForms.BunifuLabel groupBox4;
        private Bunifu.UI.WinForms.BunifuPictureBox bunifuPictureBox3;
    }
}