//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Examen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdditionalDocuments
    {
        public int ID { get; set; }
        public Nullable<int> fk { get; set; }
        public string SNILS { get; set; }
        public string POLIS { get; set; }
        public string INN { get; set; }
        public string KPP { get; set; }
        public string TrudKnijka { get; set; }
        public string MedKnikjka { get; set; }
    
        public virtual Sotrudnik Sotrudnik { get; set; }
    }
}
