//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Examen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Experience
    {
        public int ID { get; set; }
        public Nullable<int> FK_Sotrudnik { get; set; }
        public string obchyi_day { get; set; }
        public string obchyi_month { get; set; }
        public string obchyi_year { get; set; }
        public string nepreryvniy_day { get; set; }
        public string nepreryvniy_month { get; set; }
        public string nepreryvniy_year { get; set; }
        public string vislugalet_day { get; set; }
        public string vislugalet_month { get; set; }
        public string vislugalet_year { get; set; }
        public Nullable<System.DateTime> stajrabotyposostoyaniyna { get; set; }
        public string del { get; set; }
    
        public virtual Sotrudnik Sotrudnik { get; set; }
    }
}
