//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Examen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Obrazovanie
    {
        public int ID_OB { get; set; }
        public Nullable<int> fk_kod_sotrudnika { get; set; }
        public string obrazovanie1 { get; set; }
        public string nazvanieuchrejdeniya { get; set; }
        public string kvalifikachiyapoObrazovaniyu { get; set; }
        public string nazvanieuchrejdeniya2 { get; set; }
        public string kvalifikachiyapoObrazovaniyu2 { get; set; }
        public string poslevuzovoe { get; set; }
        public string professiaOsnova { get; set; }
        public string professiaDopolnitel { get; set; }
    
        public virtual Sotrudnik Sotrudnik { get; set; }
    }
}
