//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Examen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int ID { get; set; }
        public Nullable<int> ZayvleniyJob { get; set; }
        public Nullable<int> Users { get; set; }
        public Nullable<System.DateTime> DateOrders { get; set; }
        public Nullable<int> Transaction { get; set; }
    
        public virtual Transactionprogram Transactionprogram { get; set; }
        public virtual usersProgram usersProgram { get; set; }
        public virtual ZayvleniyJob ZayvleniyJob1 { get; set; }
    }
}
