//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Examen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Otpusk
    {
        public int ID { get; set; }
        public Nullable<int> FK_sotrudnik { get; set; }
        public string vid_otpuska { get; set; }
        public Nullable<System.DateTime> period_s { get; set; }
        public Nullable<System.DateTime> period_po { get; set; }
        public string day { get; set; }
        public Nullable<System.DateTime> S_kakogo { get; set; }
        public Nullable<System.DateTime> po_kakoe { get; set; }
        public string prichina { get; set; }
    
        public virtual Sotrudnik Sotrudnik { get; set; }
    }
}
