//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Examen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Passport
    {
        public int ID { get; set; }
        public Nullable<int> FK_Sotrudnik { get; set; }
        public string nomer_pasporta { get; set; }
        public Nullable<System.DateTime> datavidachi { get; set; }
        public Nullable<System.DateTime> dataregistrachii_po_mestu { get; set; }
        public string vidan { get; set; }
        public string adressjitelstva_popasportu { get; set; }
        public string aress_fakticheskiy { get; set; }
    
        public virtual Sotrudnik Sotrudnik { get; set; }
    }
}
