//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Examen.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class doljnost
    {
        public int ID_D { get; set; }
        public Nullable<int> fk_kod_sotrudnik { get; set; }
        public string naimenoviy_doljnosti { get; set; }
        public string s_kogo { get; set; }
        public string po_kokoe { get; set; }
        public Nullable<int> kol_vo { get; set; }
        public string otvetstveniy { get; set; }
    }
}
