//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Examen.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class usersProgram
    {
        public int ID_dol { get; set; }
        public string loginI { get; set; }
        public string PasI { get; set; }
        public string acces { get; set; }
        public byte[] Avatar { get; set; }
        public string Email { get; set; }
        public string Ima { get; set; }
        public string Family { get; set; }
        public string Oth { get; set; }
    }
}
