//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Examen.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Waruchet
    {
        public int ID { get; set; }
        public Nullable<int> FK_sotrudnik { get; set; }
        public string Kategorya { get; set; }
        public string Zvanie { get; set; }
        public string Sostav { get; set; }
        public string kod_VUS { get; set; }
        public string Sostoyanie_voinskogo { get; set; }
        public string Nazvanie_komisariata { get; set; }
        public string Kategoria { get; set; }
    
        public virtual Sotrudnik Sotrudnik { get; set; }
    }
}
