//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Examen.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZayvleniyJob
    {
        public int ID { get; set; }
        public string Ima { get; set; }
        public string Family { get; set; }
        public string Oth { get; set; }
        public string Doljnost { get; set; }
        public string Status { get; set; }
        public string del { get; set; }
    }
}
